package com.itgrids.partyanalyst.dto;

import java.util.ArrayList;
import java.util.List;

public class SurveyReportVO1 {

	private Long userid;
	private String userName;
	private Long count = 0L;
	private List<SurveyReportVO> subList = new ArrayList<SurveyReportVO>();
	private String surveyDate;
	private String partNo;
	private Long boothId;
	private Long voterId;
	private SurveyReportVO dataCollector;
	private SurveyReportVO verifier;
	private SurveyReportVO thirdParty;
	private SurveyReportVO panchayatDetails;
	private String voterName;
	private String cadre;
	private String influencePeople;
 	private String caste;
    private String localArea;
    private Long hamletId;
    private String hamletName;
    private String userType;
    private Long userTypeId;
    private Long casteId;
    private Long totalVoters;
    private boolean cadreMatched;
    private boolean influencePeopleMatched;
    private boolean localAreaMatched;
    private boolean hamletMatched;
    private boolean casteMatched;
    private Long surveyDetailsInfoId;
    private String voterIDCardNo;
    private String verified;
	private String surveyDate1;
	private Long matchedCount;
	private Long unmatchedCount;
	private String mobileNo;
	private Long id;
	private String name;
    private String comment;
    private Long dcWardId;
    private Long dvWardId;
	private Long readyForReviewCount = 0L;
	private Long casteMatchedCount = 0l;
	private Long casteNotMatchedCount =0l;
	private Long mobileMatchedCount =0l;
	private Long mobileNotMatchedCount =0l;
	private Long boothCount = 0l;
	private Long hamletCount = 0l;
	private Long casteCount = 0l;
	private String mandalName;
	private String panchayatName;
	private String villageCovered;
	private Long mobileNoCount =0l;
	private List<GenericVO> genericVOList = new ArrayList<GenericVO>();
	private List<GenericVO> genericVOList1 = new ArrayList<GenericVO>();
	private String percent;
	private Long panchayatCount =0l;
	private Long panchayatNotCompleteCount = 0l;
	private List<Long> completeIds = new ArrayList<Long>();
	private List<Long> notCompleteIds = new ArrayList<Long>();
	private Long casteCollectedCount = 0L;
	private Long hamletCollectedCount = 0L;
	private Long mobileNumberCollectedCount = 0L;
	private String startTime;
	private String endTime;
	private Long totalCollectedCount;
	private String totalCollectedPercent;
	private Long processingCount = 0L;
	private Long startedCount;
	private Long completedCount = 0L;
	private Long wmCompletedCount = 0L;
	private Long dvProcessingCount = 0L;
	private Long dvCompletedCount = 0L;
	private Long notStartedCount = 0L;
	private Long actualProcessingCount = 0L;
	private Long activeUsersCount = 0L;
	private Long inActiveUsersCount = 0L;
	private String casteErrorPercent;
	private String dcCaste;
	private String wmCaste;
	private String status;
	private String MobileNumber; 
	private String mobileStatus;
	private Long thirdPartyProcessing = 0L;
	private Long thirdPartyCompleted = 0L;
	private Long thirdpartyReady = 0L;
	private Long houseNoCount;
	private Long tpWebMonitoringProcessing = 0L;
	private Long tpWebMonitoringCompleted = 0L;
	private Long errorCount = 0L;
	private boolean forThirdParty;
	private Long statusId;
	private Long wardId;
	private String wardName ; 
	private CasteCollectedDetailsVO dcDetails = new CasteCollectedDetailsVO();
	private CasteCollectedDetailsVO dvDetails = new CasteCollectedDetailsVO();
	private CasteCollectedDetailsVO wmDcDetails = new CasteCollectedDetailsVO();
	private CasteCollectedDetailsVO wmDvDetails = new CasteCollectedDetailsVO();
	private List<String> ctpMobileNoList = new ArrayList<String>(); 
	private List<String> ceoMobileNoList = new ArrayList<String>();
	private List<String> dataMobileNoList = new ArrayList<String>() ;
	private List<String> surveyMobileNoList = new ArrayList<String>();
	private Long ctpMobileStatus;
	private Long ceoMobileStatus;
	private Long surveyMobileStatus;
	private Long dataMobileStatus;
}
