<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>



<div class="selectHeading">
	<span class="selectDivStyle">AndhraPradesh Districts</span>
	<span style="margin-left: 5px;">Know About Your District</span>
	<!--<select class="selectBoxWidth" id="districtList_Himachal Pradesh" name="district">
	<option value="0">Select District</option>
    <option value="311">Dhalai</option>
	<option value="309">Gomati</option>
	<option value="308">Khowai</option>
	<option value="313">North Tripura</option>
	<option value="307">Sepahijala</option>
	<option value="310">South Tripura</option>
	<option value="312">Unakoti</option>
	<option value="306">West Tripura</option>
   </select>-->
   
   <select id="districtList_d" class="selectBoxWidth" name="district">
<option value="0">Select District</option>
<option value="1">Adilabad</option>
<option value="22">Anantapur</option>
<option value="23">Chittoor</option>
<option value="20">Cuddapah</option>
<option value="14">East Godavari</option>
<option value="17">Guntur</option>
<option value="5">Hyderabad</option>
<option value="3">Karimnagar</option>
<option value="10">Khammam</option>
<option value="16">Krishna</option>
<option value="21">Kurnool</option>
<option value="7">Mahbubnagar</option>
<option value="4">Medak</option>
<option value="8">Nalgonda</option>
<option value="19">Nellore</option>
<option value="2">Nizamabad</option>
<option value="18">Prakasam</option>
<option value="6">Rangareddi</option>
<option value="11">Srikakulam</option>
<option value="13">Visakhapatnam</option>
<option value="12">Vizianagaram</option>
<option value="9">Warangal</option>
<option value="15">West Godavari</option>
</select>
   <div id="alertMessage_dist_Himachal Pradesh"></div>

	<div class="view-results"><a onclick="navigateToDistrictPageFrmSpeclPge('districtList_d','alertMessage_dist_Himachal Pradesh')" href="javascript:{}">view results</a></div>


</div>
<div class="selectHeading">
	<span class="selectDivStyle">AndhraPradesh Constituencies </span>
	<span style="margin-left: 12px;">Know About Your Assembly Constituency</span>
<select class="selectBoxWidth" id="constituency_ap" name="constituency">
<option value="0">Select Constituency</option>
<option value='8'>SIRPUR</option>
<option value='4'>CHENNUR</option>
<option value='295'>BELLAMPALLI</option>
<option value='296'>MANCHERIAL</option>
<option value='2'>ASIFABAD</option>
<option value='5'>KHANAPUR</option>
<option value='1'>ADILABAD</option>
<option value='3'>BOATH</option>
<option value='7'>NIRMAL</option>
<option value='6'>MUDHOLE</option>
<option value='10'>ARMOOR</option>
<option value='13'>BODHAN</option>
<option value='15'>JUKKAL</option>
<option value='12'>BANSWADA</option>
<option value='18'>YELLAREDDY</option>
<option value='16'>KAMAREDDY</option>
<option value='342'>NIZAMABAD URBAN</option>
<option value='343'>NIZAMABAD RURAL</option>
<option value='11'>BALKONDA</option>
<option value='321'>KORATLA</option>
<option value='23'>JAGTIAL</option>
<option value='322'>DHARMAPURI</option>
<option value='318'>RAMAGUNDAM</option>
<option value='26'>MANTHANI</option>
<option value='30'>PEDDAPALLI</option>
<option value='24'>KARIMNAGAR</option>
<option value='20'>CHOPPADANDI</option>
<option value='323'>VEMULAWADA</option>
<option value='31'>SIRCILLA</option>
<option value='319'>MANAKONDUR</option>
<option value='21'>HUZURABAD</option>
<option value='320'>HUSNABAD</option>
<option value='40'>SIDDIPET</option>
<option value='35'>MEDAK</option>
<option value='36'>NARAYANKHED</option>
<option value='32'>ANDOLE</option>
<option value='37'>NARSAPUR</option>
<option value='41'>ZAHIRABAD</option>
<option value='39'>SANGAREDDY</option>
<option value='337'>PATANCHERU</option>
<option value='336'>DUBBAK</option>
<option value='34'>GAJWEL</option>
<option value='57'>MEDCHAL</option>
<option value='367'>MALKAJGIRI</option>
<option value='345'>QUTHBULLAPUR</option>
<option value='346'>KUKATPALLY</option>
<option value='347'>UPPAL</option>
<option value='56'>IBRAHIMPATNAM</option>
<option value='348'>LAL BAHADUR NAGAR</option>
<option value='349'>MAHESWARAM</option>
<option value='351'>RAJENDRANAGAR</option>
<option value='350'>SERLINGAMPALLY</option>
<option value='55'>CHEVELLA</option>
<option value='58'>PARGI</option>
<option value='60'>VIKARABAD</option>
<option value='59'>TANDUR</option>
<option value='50'>MUSHEERABAD</option>
<option value='49'>MALAKPET</option>
<option value='315'>AMBERPET</option>
<option value='47'>KHAIRATABAD</option>
<option value='314'>JUBILEE HILLS</option>
<option value='51'>SANATHNAGAR</option>
<option value='316'>NAMPALLY</option>
<option value='46'>KARWAN</option>
<option value='317'>GOSHAMAHAL</option>
<option value='44'>CHARMINAR</option>
<option value='43'>CHANDRAYANGUTTA</option>
<option value='54'>YAKUTPURA</option>
<option value='313'>BAHADURPURA</option>
<option value='52'>SECUNDERABAD</option>
<option value='53'>SECUNDERABAD CANTONMENT</option>
<option value='66'>KODANGAL</option>
<option value='335'>NARAYANPET</option>
<option value='68'>MAHBUBNAGAR</option>
<option value='64'>JADCHERLA</option>
<option value='369'>DEVARKADRA</option>
<option value='69'>MAKTHAL</option>
<option value='73'>WANAPARTHY</option>
<option value='63'>GADWAL</option>
<option value='62'>ALAMPUR</option>
<option value='70'>NAGARKURNOOL</option>
<option value='61'>ACHAMPET</option>
<option value='65'>KALWAKURTHI</option>
<option value='71'>SHADNAGAR</option>
<option value='67'>KOLLAPUR</option>
<option value='77'>DEVERKONDA</option>
<option value='338'>NAGARJUNA SAGAR</option>
<option value='79'>MIRYALGUDA</option>
<option value='339'>HUZURNAGAR</option>
<option value='78'>KODAD</option>
<option value='84'>SURYAPET</option>
<option value='82'>NALGONDA</option>
<option value='80'>MUNGODE</option>
<option value='75'>BHONGIR</option>
<option value='81'>NAKREKAL</option>
<option value='85'>TUNGATURTHI</option>
<option value='74'>ALAIR</option>
<option value='89'>JANGAON</option>
<option value='87'>GHANPUR</option>
<option value='362'>PALAKURTHI</option>
<option value='86'>DORNAKAL</option>
<option value='91'>MAHBUBABAD</option>
<option value='93'>NARSAMPET</option>
<option value='94'>PARKAL</option>
<option value='363'>WARANGAL WEST</option>
<option value='364'>WARANGAL EAST</option>
<option value='97'>WARDHANNAPET</option>
<option value='365'>BHUPALPALLE</option>
<option value='92'>MULUG</option>
<option value='324'>PINAPAKA</option>
<option value='107'>YELLANDU</option>
<option value='101'>KHAMMAM</option>
<option value='104'>PALAIR</option>
<option value='103'>MADHIRA</option>
<option value='325'>WYRA</option>
<option value='105'>SATHUPALLI</option>
<option value='102'>KOTHAGUDEM</option>
<option value='326'>ASWARAOPET</option>
<option value='100'>BHADRACHALAM</option>
<option value='111'>ICHAPURAM</option>
<option value='352'>PALASA</option>
<option value='117'>TEKKALI</option>
<option value='114'>PATHAPATNAM</option>
<option value='116'>SRIKAKULAM</option>
<option value='108'>AMADALAVALASA</option>
<option value='109'>ETCHERLA</option>
<option value='112'>NARASANNAPETA</option>
<option value='353'>RAJAM</option>
<option value='113'>PALAKONDA</option>
<option value='360'>KURUPAM</option>
<option value='124'>PARVATHIPURAM</option>
<option value='125'>SALUR</option>
<option value='122'>BOBBILI</option>
<option value='120'>CHEEPURUPALLI</option>
<option value='121'>GAJAPATHINAGARAM</option>
<option value='361'>NELLIMARLA</option>
<option value='129'>VIZIANAGARAM</option>
<option value='127'>SRUNGAVARAPUKOTA</option>
<option value='368'>BHIMILI</option>
<option value='354'>VISAKHAPATNAM EAST</option>
<option value='355'>VISAKHAPATNAM SOUTH</option>
<option value='356'>VISAKHAPATNAM NORTH</option>
<option value='357'>VISAKHAPATNAM WEST</option>
<option value='358'>GAJUWAKA</option>
<option value='134'>CHODAVARAM</option>
<option value='136'>MADUGULA</option>
<option value='359'>ARAKU VALLEY</option>
<option value='138'>PADERU</option>
<option value='133'>ANAKAPALLI</option>
<option value='141'>PENDURTHI</option>
<option value='135'>ELAMANCHILI</option>
<option value='140'>PAYAKARAOPETA</option>
<option value='137'>NARSIPATNAM</option>
<option value='163'>TUNI</option>
<option value='157'>PRATHIPAD</option>
<option value='156'>PITHAPURAM</option>
<option value='307'>KAKINADA RURAL</option>
<option value='155'>PEDDAPURAM</option>
<option value='147'>ANAPARTHY</option>
<option value='308'>KAKINADA CITY</option>
<option value='159'>RAMACHANDRAPURAM</option>
<option value='153'>MUMMIDIVARAM</option>
<option value='146'>Amalapuram</option>
<option value='160'>RAZOLE</option>
<option value='310'>GANNAVARAM</option>
<option value='152'>KOTHAPETA</option>
<option value='309'>MANDAPETA</option>
<option value='303'>RAJANAGARAM</option>
<option value='304'>RAJAHMUNDRY CITY</option>
<option value='305'>RAJAHMUNDRY RURAL</option>
<option value='149'>JAGGAMPETA</option>
<option value='306'>RAMPACHODAVARAM</option>
<option value='172'>KOVVUR</option>
<option value='366'>NIDADAVOLE</option>
<option value='181'>ACHANTA</option>
<option value='174'>PALACOLE</option>
<option value='173'>NARASAPUR</option>
<option value='167'>BHIMAVARAM</option>
<option value='179'>UNDI</option>
<option value='178'>TANUKU</option>
<option value='177'>TADEPALLIGUDEM</option>
<option value='180'>UNGUTUR</option>
<option value='169'>DENDULUR</option>
<option value='170'>ELURU</option>
<option value='171'>GOPALPURAM</option>
<option value='176'>POLAVARAM</option>
<option value='168'>CHINTALAPUDI</option>
<option value='194'>TIRUVURU</option>
<option value='193'>NUZVID</option>
<option value='184'>GANNAVARAM</option>
<option value='185'>GUDIVADA</option>
<option value='187'>KAIKALUR</option>
<option value='327'>PEDANA</option>
<option value='328'>MACHILIPATNAM</option>
<option value='182'>AVANIGADDA</option>
<option value='329'>PAMARRU</option>
<option value='330'>PENAMALURU</option>
<option value='196'>VIJAYAWADA WEST</option>
<option value='331'>VIJAYAWADA CENTRAL</option>
<option value='195'>VIJAYAWADA EAST</option>
<option value='191'>MYLAVARAM</option>
<option value='192'>NANDIGAMA</option>
<option value='186'>JAGGAYYAPET</option>
<option value='210'>PEDDAKURAPADU</option>
<option value='215'>TADIKONDA</option>
<option value='206'>MANGALAGIRI</option>
<option value='211'>PONNUR</option>
<option value='217'>VEMURU</option>
<option value='213'>REPALLE</option>
<option value='216'>TENALI</option>
<option value='209'>BAPATLA</option>
<option value='212'>PRATHIPADU</option>
<option value='312'>GUNTUR WEST</option>
<option value='311'>GUNTUR EAST</option>
<option value='199'>CHILAKALURIPET</option>
<option value='208'>NARASARAOPET</option>
<option value='214'>SATTENAPALLI</option>
<option value='207'>VINUKONDA</option>
<option value='203'>GURZALA</option>
<option value='205'>MACHERLA</option>
<option value='344'>YERRAGONDAPALEM</option>
<option value='221'>DARSI</option>
<option value='228'>PARCHUR</option>
<option value='218'>ADDANKI</option>
<option value='219'>CHIRALA</option>
<option value='229'>SANTHANUTHALAPADU</option>
<option value='227'>ONGOLE</option>
<option value='223'>KANDUKUR</option>
<option value='225'>KONDEPI</option>
<option value='226'>MARKAPUR</option>
<option value='222'>GIDDALUR</option>
<option value='224'>KANIGIRI</option>
<option value='232'>KAVALI</option>
<option value='241'>ATMAKUR</option>
<option value='233'>KOVUR</option>
<option value='340'>NELLORE CITY</option>
<option value='341'>NELLORE RURAL</option>
<option value='236'>SARVEPALLI</option>
<option value='231'>GUDUR</option>
<option value='237'>SULLURPET</option>
<option value='239'>VENKATAGIRI</option>
<option value='238'>UDAYAGIRI</option>
<option value='242'>BADVEL</option>
<option value='252'>RAJAMPET</option>
<option value='243'>KADAPA</option>
<option value='246'>KODUR</option>
<option value='248'>RAYACHOTY</option>
<option value='251'>PULIVENDLA</option>
<option value='245'>KAMALAPURAM</option>
<option value='244'>JAMMALAMADUGU</option>
<option value='250'>PRODDATUR</option>
<option value='249'>MYDUKUR</option>
<option value='254'>ALLAGADDA</option>
<option value='332'>SRISAILAM</option>
<option value='261'>NANDIKOTKUR</option>
<option value='260'>KURNOOL</option>
<option value='263'>PANYAM</option>
<option value='262'>NANDYAL</option>
<option value='333'>BANAGANAPALLE</option>
<option value='257'>DHONE</option>
<option value='264'>PATTIKONDA</option>
<option value='258'>KODUMUR</option>
<option value='265'>YEMMIGANUR</option>
<option value='334'>MANTRALAYAM</option>
<option value='253'>ADONI</option>
<option value='255'>ALUR</option>
<option value='276'>RAYADURG</option>
<option value='279'>URAVAKONDA</option>
<option value='297'>GUNTAKAL</option>
<option value='278'>TADPATRI</option>
<option value='277'>SINGANAMALA</option>
<option value='298'>ANANTAPUR URBAN</option>
<option value='272'>KALYANDURG</option>
<option value='299'>RAPTADU</option>
<option value='273'>MADAKASIRA</option>
<option value='270'>HINDUPUR</option>
<option value='275'>PENUKONDA</option>
<option value='300'>PUTTAPARTHI</option>
<option value='267'>DHARMAVARAM</option>
<option value='271'>KADIRI</option>
<option value='290'>THAMBALLAPALLE</option>
<option value='285'>PILERU</option>
<option value='294'>MADANPALLE</option>
<option value='286'>PUNGANUR</option>
<option value='280'>CHANDRAGIRI</option>
<option value='291'>TIRUPATI</option>
<option value='289'>SRIKALAHASTI</option>
<option value='288'>SATYAVEDU</option>
<option value='283'>NAGARI</option>
<option value='301'>GANGADHARA NELLORE</option>
<option value='281'>CHITTOOR</option>
<option value='302'>PUTHALAPATTU</option>
<option value='284'>Palamaner</option>
<option value='282'>KUPPAM</option>

</select>
<div id="alertMessage_cons_Himachal Pradesh"></div>

<div class="view-results"><a onclick="navigateToConstituencyPageFrmSpeclPge('constituency_ap','alertMessage_cons_Himachal Pradesh')" href="javascript:{}">view constituency</a></div>
</div>

