<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>



<div class="selectHeading">
	<span class="selectDivStyle">Madhya Pradesh Districts</span>
	<span style="margin-left: 5px;">Know About Your District</span>
	<select class="selectBoxWidth" id="districtList_Himachal Pradesh" name="district">
	<option value="0">Select District</option>
   <option value="390">Sheopur	</option>	
<option value="391">Morena	</option>	
<option value="392">Bhind	</option>	
<option value="393">Gwalior	</option>	
<option value="394">Datia	</option>	
<option value="395">Shivpuri	</option>	
<option value="396">Guna	</option>	
<option value="397">Tikamgarh	</option>	
<option value="398">Chhatarpur	</option>	
<option value="399">Panna	</option>	
<option value="400">Sagar	</option>	
<option value="401">Damoh	</option>	
<option value="402">Satna	</option>	
<option value="403">Rewa	</option>	
<option value="404">Umaria	</option>	
<option value="405">Shahdol	</option>	
<option value="406">Sidhi	</option>	
<option value="407">Neemuch	</option>	
<option value="408">Mandsaur	</option>	
<option value="409">Ratlam	</option>	
<option value="410">Ujjain	</option>	
<option value="411">Shajapur	</option>	
<option value="412">Dewas	</option>	
<option value="413">Jhabua	</option>	
<option value="414">Dhar	</option>	
<option value="415">Indore	</option>	
<option value="416">West Nimar	</option>	
<option value="417">Barwani	</option>	
<option value="418">East Nimar	</option>	
<option value="419">Rajgarh	</option>	
<option value="420">Vidisha	</option>	
<option value="421">Bhopal	</option>	
<option value="422">Sehore	</option>	
<option value="423">Raisen	</option>	
<option value="424">Betul	</option>	
<option value="425">Harda	</option>	
<option value="426">Hoshangabad	</option>	
<option value="427">Katni	</option>	
<option value="428">Jabalpur	</option>	
<option value="429">Narsimhapur	</option>	
<option value="430">Dindori	</option>	
<option value="431">Mandla	</option>	
<option value="432">Chhindwara	</option>	
<option value="433">Seoni	</option>	
<option value="434">Balaghat	</option>	

   </select>
   <div id="alertMessage_dist_Himachal Pradesh"></div>

	<div class="view-results"><a onclick="navigateToDistrictPageFrmSpeclPge('districtList_Himachal Pradesh','alertMessage_dist_Himachal Pradesh')" href="javascript:{}">view results</a></div>


</div>
<div class="selectHeading">
	<span class="selectDivStyle">Madhya Pradesh Constituencies </span>
	<span style="margin-left: 12px;">Know About Your Assembly Constituency</span>
<select class="selectBoxWidth" id="constituency_Himachal Pradesh" name="constituency">
<option value="0">Select Constituency</option>
<option value="	40935">Sheopur	</option>
	<option value="	40936">Vijaypur	</option>
	<option value="	40937">Sabalgarh	</option>
	<option value="	40938">Joura	</option>
	<option value="	40939">Sumawali	</option>
	<option value="	40940">Morena	</option>
	<option value="	40941">Dimani	</option>
	<option value="	40942">Ambah	</option>
	<option value="	40943">Ater	</option>
	<option value="	40944">Bhind	</option>
	<option value="	40945">Lahar	</option>
	<option value="	40946">Mehgaon	</option>
	<option value="	40947">Gohad	</option>
	<option value="	40948">Gwalior Rural	</option>
	<option value="	40949">Gwalior	</option>
	<option value="	40950">Gwalior East	</option>
	<option value="	40951">Gwalior South	</option>
	<option value="	40952">Bhitarwar	</option>
	<option value="	40953">Dabra	</option>
	<option value="	40954">Sewda	</option>
	<option value="	40955">Bhander	</option>
	<option value="	40956">Datia	</option>
	<option value="	40957">Karera	</option>
	<option value="	40958">Pohari	</option>
	<option value="	40959">Shivpuri	</option>
	<option value="	40960">Pichhore	</option>
	<option value="	40961">Kolaras	</option>
	<option value="	40962">Bamori	</option>
	<option value="	40963">Guna	</option>
	<option value="	40964">Chachoura	</option>
	<option value="	40965">Raghogarh	</option>
	<option value="	40966">Ashok Nagar	</option>
	<option value="	40967">Chanderi	</option>
	<option value="	40968">Mungaoli	</option>
	<option value="	40969">Bina	</option>
	<option value="	40970">Khurai	</option>
	<option value="	40971">Surkhi	</option>
	<option value="	40972">Deori	</option>
	<option value="	40973">Rehli	</option>
	<option value="	40974">Naryoli	</option>
	<option value="	40975">Sagar	</option>
	<option value="	40976">Banda	</option>
	<option value="	40977">Tikamgarh	</option>
	<option value="	40978">Jatara	</option>
	<option value="	40979">Prithvipur	</option>
	<option value="	40980">Niwari	</option>
	<option value="	40981">Khargapur	</option>
	<option value="	40982">Maharajpur	</option>
	<option value="	40983">Chandla	</option>
	<option value="	40984">Rajnagar	</option>
	<option value="	40985">Chhatarpur	</option>
	<option value="	40986">Bijawar	</option>
	<option value="	40987">Malhara	</option>
	<option value="	40988">Pathariya	</option>
	<option value="	40989">Damoh	</option>
	<option value="	40990">Jabera	</option>
	<option value="	40991">Hatta	</option>
	<option value="	40992">Pawai	</option>
	<option value="	40993">Gunnaor	</option>
	<option value="	40994">Panna	</option>
	<option value="	40995">Chitrakoot	</option>
	<option value="	40996">Raigaon	</option>
	<option value="	40997">Satna	</option>
	<option value="	40998">Nagod	</option>
	<option value="	40999">Maihar	</option>
	<option value="	41000">Amarpatan	</option>
	<option value="	41001">Rampur Baghelan	</option>
	<option value="	41002">Sirmour	</option>
	<option value="	41003">Semariya	</option>
	<option value="	41004">Teonthar	</option>
	<option value="	41005">Mauganj	</option>
	<option value="	41006">Deotalab	</option>
	<option value="	41007">Mangawan	</option>
	<option value="	41008">Rewa	</option>
	<option value="	41009">Gurh	</option>
	<option value="	41010">Churhat	</option>
	<option value="	41011">Sidhi	</option>
	<option value="	41012">Sihawal	</option>
	<option value="	41013">Chitrangi	</option>
	<option value="	41014">Singrauli	</option>
	<option value="	41015">Devsar	</option>
	<option value="	41016">Dhauhani	</option>
	<option value="	41017">Beohari	</option>
	<option value="	41018">Jaisinghnagar	</option>
	<option value="	41019">Jaitpur	</option>
	<option value="	41020">Kotma	</option>
	<option value="	41021">Anuppur	</option>
	<option value="	41022">Pushprajgarh	</option>
	<option value="	41023">Bandhavgarh	</option>
	<option value="	41024">Manpur	</option>
	<option value="	41025">Barwara	</option>
	<option value="	41026">Vijayraghogarh	</option>
	<option value="	41027">Murwara	</option>
	<option value="	41028">Bahoriband	</option>
	<option value="	41029">Patan	</option>
	<option value="	41030">Bargi	</option>
	<option value="	41031">Jabalpur Purba	</option>
	<option value="	41032">Jabalpur Uttar	</option>
	<option value="	41033">Jabalpur Cantt.	</option>
	<option value="	41034">Jabalpur Paschim	</option>
	<option value="	41035">Panagar	</option>
	<option value="	41036">Sihora	</option>
	<option value="	41037">Shahpura	</option>
	<option value="	41038">Dindori	</option>
	<option value="	41039">Bichhiya	</option>
	<option value="	41040">Niwas	</option>
	<option value="	41041">Mandla	</option>
	<option value="	41042">Baihar	</option>
	<option value="	41043">Lanji	</option>
	<option value="	41044">Paraswada	</option>
	<option value="	41045">Balaghat	</option>
	<option value="	41046">Waraseoni	</option>
	<option value="	41047">Katangi	</option>
	<option value="	41048">Barghat	</option>
	<option value="	41049">Seoni	</option>
	<option value="	41050">Keolari	</option>
	<option value="	41051">Lakhnadon	</option>
	<option value="	41052">Gotegaon	</option>
	<option value="	41053">Narsingpur	</option>
	<option value="	41054">Tendukheda	</option>
	<option value="	41055">Gadarwara	</option>
	<option value="	41056">Junnardeo	</option>
	<option value="	41057">Amarwara	</option>
	<option value="	41058">Churai	</option>
	<option value="	41059">Saunsar	</option>
	<option value="	41060">Chhindwara	</option>
	<option value="	41061">Parasia	</option>
	<option value="	41062">Pandhurna	</option>
	<option value="	41063">Multai	</option>
	<option value="	41064">Amla	</option>
	<option value="	41065">Betul	</option>
	<option value="	41066">Ghoradongri	</option>
	<option value="	41067">Bhainsdehi	</option>
	<option value="	41068">Timarni	</option>
	<option value="	41069">Harda	</option>
	<option value="	41070">Seoni Malwa	</option>
	<option value="	41071">Hoshangabad	</option>
	<option value="	41072">Sohagpur	</option>
	<option value="	41073">Pipariya	</option>
	<option value="	41074">Udaipura	</option>
	<option value="	41075">Bhojpur	</option>
	<option value="	41076">Sanchi	</option>
	<option value="	41077">Silwani	</option>
	<option value="	41078">Vidisha	</option>
	<option value="	41079">Basoda	</option>
	<option value="	41080">Kurwai	</option>
	<option value="	41081">Sironj	</option>
	<option value="	41082">Shamshabad	</option>
	<option value="	41083">Berasia	</option>
	<option value="	41084">Bhopal Uttar	</option>
	<option value="	41085">Narela	</option>
	<option value="	41086">Bhopal Dakshin Paschim	</option>
	<option value="	41087">Bhopal Madhya	</option>
	<option value="	41088">Govindpura	</option>
	<option value="	41089">Huzur	</option>
	<option value="	41090">Budhni	</option>
	<option value="	41091">Ashta	</option>
	<option value="	41092">Ichhawar	</option>
	<option value="	41093">Sehore	</option>
	<option value="	41094">Narsinghgarh	</option>
	<option value="	41095">Biaora	</option>
	<option value="	41096">Rajgarh	</option>
	<option value="	41097">Khilchipur	</option>
	<option value="	41098">Sarangpur	</option>
	<option value="	41099">Susner	</option>
	<option value="	41100">Agar	</option>
	<option value="	41101">Shajapur	</option>
	<option value="	41102">Shujalpur	</option>
	<option value="	41103">Kalapipal	</option>
	<option value="	41104">Sonkatch	</option>
	<option value="	41105">Dewas	</option>
	<option value="	41106">Hatpipliya	</option>
	<option value="	41107">Khategaon	</option>
	<option value="	41108">Bagali	</option>
	<option value="	41109">Mandhata	</option>
	<option value="	41110">Harsud	</option>
	<option value="	41111">Khandwa	</option>
	<option value="	41112">Pandhana	</option>
	<option value="	41113">Nepanagar	</option>
	<option value="	41114">Burhanpur	</option>
	<option value="	41115">Bhikangaon	</option>
	<option value="	41116">Badwah	</option>
	<option value="	41117">Maheshwar	</option>
	<option value="	41118">Kasrawad	</option>
	<option value="	41119">Khargone	</option>
	<option value="	41120">Bhagwanpura	</option>
	<option value="	41121">Sendhawa	</option>
	<option value="	41122">Rajpur	</option>
	<option value="	41123">Pansemal	</option>
	<option value="	41124">Badwani	</option>
	<option value="	41125">Alirajpur	</option>
	<option value="	41126">Jobat	</option>
	<option value="	41127">Jhabua	</option>
	<option value="	41128">Thandla	</option>
	<option value="	41129">Petlawad	</option>
	<option value="	41130">Sardarpur	</option>
	<option value="	41131">Gandhwani	</option>
	<option value="	41132">Kukshi	</option>
	<option value="	41133">Manawar	</option>
	<option value="	41134">Dharampuri	</option>
	<option value="	41135">Dhar	</option>
	<option value="	41136">Badnawar	</option>
	<option value="	41137">Depalpur	</option>
	<option value="	41138">Indore 1	</option>
	<option value="	41139">Indore 2	</option>
	<option value="	41140">Indore 3	</option>
	<option value="	41141">Indore 4	</option>
	<option value="	41142">Indore 5	</option>
	<option value="	41143">Dr Ambedkar Nagar Mhow	</option>
	<option value="	41144">Rau	</option>
	<option value="	41145">Sanwer	</option>
	<option value="	41146">Nagada Khachrod	</option>
	<option value="	41147">Mahidpur	</option>
	<option value="	41148">Tarana	</option>
	<option value="	41149">Ghatiya	</option>
	<option value="	41150">Ujjain Uttar	</option>
	<option value="	41151">Ujjain Dakshin	</option>
	<option value="	41152">Badnagar	</option>
	<option value="	41153">Ratlam Rural	</option>
	<option value="	41154">Ratlam City	</option>
	<option value="	41155">Sailana	</option>
	<option value="	41156">Jaora	</option>
	<option value="	41157">Alot	</option>
	<option value="	41158">Mandsour	</option>
	<option value="	41159">Malhargarh	</option>
	<option value="	41160">Suwasra	</option>
	<option value="	41161">Garoth	</option>
	<option value="	41162">Manasa	</option>
	<option value="	41163">Neemuch	</option>
	<option value="	41164">Jawad	</option>

</select>
<div id="alertMessage_cons_Himachal Pradesh"></div>

<div class="view-results"><a onclick="navigateToConstituencyPageFrmSpeclPge('constituency_Himachal Pradesh','alertMessage_cons_Himachal Pradesh')" href="javascript:{}">view constituency</a></div>
</div>

