<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>



<!--<div class="selectHeading">
	<span class="selectDivStyle">AndhraPradesh Districts</span>
	<span style="margin-left: 5px;">Know About Your District</span>
	<!--<select class="selectBoxWidth" id="districtList_Himachal Pradesh" name="district">
	<option value="0">Select District</option>
    <option value="311">Dhalai</option>
	<option value="309">Gomati</option>
	<option value="308">Khowai</option>
	<option value="313">North Tripura</option>
	<option value="307">Sepahijala</option>
	<option value="310">South Tripura</option>
	<option value="312">Unakoti</option>
	<option value="306">West Tripura</option>
   </select>
   
   <select id="districtList_d" class="selectBoxWidth" name="district">
<option value="0">Select District</option>
<option value="1">Adilabad</option>
<option value="22">Anantapur</option>
<option value="23">Chittoor</option>
<option value="20">Cuddapah</option>
<option value="14">East Godavari</option>
<option value="17">Guntur</option>
<option value="5">Hyderabad</option>
<option value="3">Karimnagar</option>
<option value="10">Khammam</option>
<option value="16">Krishna</option>
<option value="21">Kurnool</option>
<option value="7">Mahbubnagar</option>
<option value="4">Medak</option>
<option value="8">Nalgonda</option>
<option value="19">Nellore</option>
<option value="2">Nizamabad</option>
<option value="18">Prakasam</option>
<option value="6">Rangareddi</option>
<option value="11">Srikakulam</option>
<option value="13">Visakhapatnam</option>
<option value="12">Vizianagaram</option>
<option value="9">Warangal</option>
<option value="15">West Godavari</option>
</select>
   <div id="alertMessage_dist_Himachal Pradesh"></div>

	<div class="view-results"><a onclick="navigateToDistrictPageFrmSpeclPge('districtList_d','alertMessage_dist_Himachal Pradesh')" href="javascript:{}">view results</a></div>


</div>-->
<div class="selectHeading">
	<span class="selectDivStyle">Parliament Constituencies </span>
	<span style="margin-left: 12px;">Know About Your Parliament Constituency</span>
<select class="selectBoxWidth" id="constituency_parliament" name="constituency">
<option value="0">Select Constituency</option>
<option value="461">Adilabad</option>
<option value="988">Agra</option>
<option value="601">Ahmedabad East</option>
<option value="602">Ahmedabad West</option>
<option value="779">Ahmednagar</option>
<option value="901">Ajmer</option>
<option value="989">Akbarpur</option>
<option value="780">Akola</option>
<option value="712">Alappuzha</option>
<option value="713">Alathur</option>
<option value="990">Aligarh</option>
<option value="1084">Alipurduars</option>
<option value="991">Allahabad</option>
<option value="1078">Almora</option>
<option value="902">Alwar</option>
<option value="463">Amalapuram</option>
<option value="637">Ambala</option>
<option value="992">Ambedkar Nagar</option>
<option value="993">Amethi</option>
<option value="781">Amravati</option>
<option value="603">Amreli</option>
<option value="883">Amritsar</option>
<option value="994">Amroha</option>
<option value="464">Anakapalli</option>
<option value="604">Anand</option>
<option value="884">Anandpur Sahib</option>
<option value="465">Anantapur</option>
<option value="656">Anantnag</option>
<option value="462">Andaman &amp; Nicobar Islands</option>
<option value="995">Aonla</option>
<option value="931">Arakkonam</option>
<option value="466">Araku</option>
<option value="1085">Arambagh</option>
<option value="932">Arani</option>
<option value="528">Araria</option>
<option value="529">Arrah</option>
<option value="512">Arunachal East</option>
<option value="513">Arunachal West</option>
<option value="1086">Asansol</option>
<option value="858">Aska</option>
<option value="715">Attingal</option>
<option value="530">Aurangabad</option>
<option value="778">Aurangabad</option>
<option value="514">Autonomous District</option>
<option value="996">Azamgarh</option>
<option value="997">Badaun</option>
<option value="676">Bagalkot</option>
<option value="998">Baghpat</option>
<option value="1087">Baharampur</option>
<option value="999">Bahraich</option>
<option value="746">Balaghat</option>
<option value="859">Balasore</option>
<option value="1000">Ballia</option>
<option value="1088">Balurghat</option>
<option value="605">Banaskantha</option>
<option value="1002">Banda</option>
<option value="677">Bangalore Central</option>
<option value="678">Bangalore North</option>
<option value="679">Bangalore Rural</option>
<option value="680">Bangalore South</option>
<option value="1089">Bangaon</option>
<option value="533">Banka</option>
<option value="1090">Bankura</option>
<option value="1003">Bansgaon</option>
<option value="903">Banswara</option>
<option value="467">Bapatla</option>
<option value="1004">Bara Banki</option>
<option value="782">Baramati</option>
<option value="657">Baramulla</option>
<option value="1091">Barasat</option>
<option value="1093">Bardhaman Durgapur</option>
<option value="1092">Bardhaman Purba</option>
<option value="606">Bardoli</option>
<option value="1005">Bareilly</option>
<option value="860">Bargarh</option>
<option value="904">Barmer</option>
<option value="515">Barpeta</option>
<option value="1094">Barrackpur</option>
<option value="1095">Basirhat</option>
<option value="580">Bastar</option>
<option value="1006">Basti</option>
<option value="885">Bathinda</option>
<option value="783">Beed</option>
<option value="535">Begusarai</option>
<option value="681">Belgaum</option>
<option value="682">Bellary</option>
<option value="1096">Berhampore</option>
<option value="861">Berhampur</option>
<option value="747">Betul</option>
<option value="1007">Bhadohi</option>
<option value="862">Bhadrak</option>
<option value="537">Bhagalpur</option>
<option value="785">Bhandara Gondiya</option>
<option value="906">Bharatpur</option>
<option value="608">Bharuch</option>
<option value="886">Bhatinda</option>
<option value="609">Bhavnagar</option>
<option value="907">Bhilwara</option>
<option value="748">Bhind</option>
<option value="786">Bhiwandi</option>
<option value="639">Bhiwani Mahendragarh</option>
<option value="469">Bhongir</option>
<option value="749">Bhopal</option>
<option value="863">Bhubaneswar</option>
<option value="683">Bidar</option>
<option value="684">Bijapur</option>
<option value="1008">Bijnor</option>
<option value="908">Bikaner</option>
<option value="581">Bilaspur</option>
<option value="1097">Birbhum</option>
<option value="1098">Bishnupur</option>
<option value="864">Bolangir</option>
<option value="1099">Bolpur</option>
<option value="1011">Bulandshahr</option>
<option value="787">Buldhana</option>
<option value="539">Buxar</option>
<option value="719">Chalakudy</option>
<option value="685">Chamarajanagar</option>
<option value="1013">Chandauli</option>
<option value="579">Chandigarh</option>
<option value="848">Chandni Chowk</option>
<option value="788">Chandrapur</option>
<option value="662">Chatra</option>
<option value="934">Chennai Central</option>
<option value="935">Chennai North</option>
<option value="936">Chennai South</option>
<option value="471">Chevella</option>
<option value="750">Chhindwara</option>
<option value="612">Chhota Udaipur</option>
<option value="937">Chidambaram</option>
<option value="686">Chikballapur</option>
<option value="687">Chikkodi</option>
<option value="689">Chitradurga</option>
<option value="472">Chittoor</option>
<option value="909">Chittorgarh</option>
<option value="910">Churu</option>
<option value="938">Coimbatore</option>
<option value="1105">Cooch Behar</option>
<option value="939">Cuddalore</option>
<option value="865">Cuttack</option>
<option value="594">Dadra &amp; Nagar Haveli</option>
<option value="613">Dahod</option>
<option value="690">Dakshina Kannada</option>
<option value="595">Daman &amp; Diu</option>
<option value="751">Damoh</option>
<option value="541">Darbhanga</option>
<option value="1106">Darjeeling</option>
<option value="911">Dausa</option>
<option value="691">Davanagere</option>
<option value="1014">Deoria</option>
<option value="752">Dewas</option>
<option value="663">Dhanbad</option>
<option value="753">Dhar</option>
<option value="940">Dharmapuri</option>
<option value="692">Dharwad</option>
<option value="1015">Dhaurahra</option>
<option value="867">Dhenkanal</option>
<option value="516">Dhubri</option>
<option value="791">Dhule</option>
<option value="1107">Diamond Harbour</option>
<option value="517">Dibrugarh</option>
<option value="941">Dindigul</option>
<option value="792">Dindori</option>
<option value="1016">Domariaganj</option>
<option value="1108">Dum Dum</option>
<option value="664">Dumka</option>
<option value="582">Durg</option>
<option value="850">East Delhi</option>
<option value="473">Eluru</option>
<option value="721">Ernakulam</option>
<option value="942">Erode</option>
<option value="1017">Etah</option>
<option value="1018">Etawah</option>
<option value="1019">Faizabad</option>
<option value="640">Faridabad</option>
<option value="887">Faridkot</option>
<option value="1020">Farrukhabad</option>
<option value="888">Fatehgarh Sahib</option>
<option value="1021">Fatehpur</option>
<option value="1022">Fatehpur Sikri</option>
<option value="1023">Firozabad</option>
<option value="889">Firozpur</option>
<option value="794">Gadchiroli Chimur</option>
<option value="616">Gandhinagar</option>
<option value="912">Ganganagar</option>
<option value="1079">Garhwal</option>
<option value="518">Gauhati</option>
<option value="1024">Gautam Buddha Nagar</option>
<option value="542">Gaya</option>
<option value="1110">Ghatal</option>
<option value="1026">Ghaziabad</option>
<option value="1027">Ghazipur</option>
<option value="1028">Ghosi</option>
<option value="665">Giridih</option>
<option value="666">Godda</option>
<option value="1029">Gonda</option>
<option value="543">Gopalganj</option>
<option value="1030">Gorakhpur</option>
<option value="695">Gulbarga</option>
<option value="754">Guna</option>
<option value="474">Guntur</option>
<option value="890">Gurdaspur</option>
<option value="641">Gurgaon</option>
<option value="755">Gwalior</option>
<option value="544">Hajipur</option>
<option value="650">Hamirpur</option>
<option value="651">Hamirpur</option>
<option value="1032">Hardoi</option>
<option value="1080">Hardwar</option>
<option value="696">Hassan</option>
<option value="1033">Hathras</option>
<option value="795">Hatkanangle</option>
<option value="697">Haveri</option>
<option value="667">Hazaribagh</option>
<option value="476">Hindupur</option>
<option value="796">Hingoli</option>
<option value="642">Hissar</option>
<option value="1111">Hooghly</option>
<option value="756">Hoshangabad</option>
<option value="891">Hoshiarpur</option>
<option value="1112">Howrah</option>
<option value="477">Hyderabad</option>
<option value="722">Idukki</option>
<option value="757">Indore</option>
<option value="842">Inner Manipur</option>
<option value="758">Jabalpur</option>
<option value="1113">Jadavpur</option>
<option value="868">Jagatsinghpur</option>
<option value="545">Jahanabad</option>
<option value="913">Jaipur</option>
<option value="914">Jaipur Rural</option>
<option value="869">Jajpur</option>
<option value="892">Jalandhar</option>
<option value="1034">Jalaun</option>
<option value="798">Jalgaon</option>
<option value="799">Jalna</option>
<option value="915">Jalore</option>
<option value="1114">Jalpaiguri</option>
<option value="658">Jammu</option>
<option value="618">Jamnagar</option>
<option value="668">Jamshedpur</option>
<option value="546">Jamui</option>
<option value="1115">Jangipur</option>
<option value="584">Janjgir Champa</option>
<option value="1036">Jaunpur</option>
<option value="917">Jhalawar Baran</option>
<option value="547">Jhanjharpur</option>
<option value="1037">Jhansi</option>
<option value="1116">Jhargram</option>
<option value="918">Jhunjhunu</option>
<option value="919">Jodhpur</option>
<option value="519">Jorhat</option>
<option value="1117">Joynagar</option>
<option value="619">Junagadh</option>
<option value="620">Kachchh</option>
<option value="478">Kadapa</option>
<option value="1038">Kairana</option>
<option value="1039">Kaiserganj</option>
<option value="479">Kakinada</option>
<option value="870">Kalahandi</option>
<option value="520">Kaliabor</option>
<option value="944">Kallakurichi</option>
<option value="800">Kalyan</option>
<option value="945">Kancheepuram</option>
<option value="871">Kandhamal</option>
<option value="652">Kangra</option>
<option value="585">Kanker</option>
<option value="1040">Kannauj</option>
<option value="946">Kanniyakumari</option>
<option value="723">Kannur</option>
<option value="1041">Kanpur</option>
<option value="548">Karakat</option>
<option value="920">Karauli Dholpur</option>
<option value="521">Karimganj</option>
<option value="480">Karimnagar</option>
<option value="643">Karnal</option>
<option value="947">Karur</option>
<option value="724">Kasaragod</option>
<option value="549">Katihar</option>
<option value="1042">Kaushambi</option>
<option value="872">Kendrapara</option>
<option value="873">Keonjhar</option>
<option value="894">Khadoor Sahib</option>
<option value="550">Khagaria</option>
<option value="760">Khajuraho</option>
<option value="481">Khammam</option>
<option value="761">Khandwa</option>
<option value="762">Khargone</option>
<option value="623">Kheda</option>
<option value="1044">Kheri</option>
<option value="669">Khunti</option>
<option value="551">Kishanganj</option>
<option value="670">Kodarma</option>
<option value="522">Kokrajhar</option>
<option value="700">Kolar</option>
<option value="804">Kolhapur</option>
<option value="1120">Kolkata Dakshin</option>
<option value="1121">Kolkata Uttar</option>
<option value="725">Kollam</option>
<option value="701">Koppal</option>
<option value="874">Koraput</option>
<option value="586">Korba</option>
<option value="921">Kota</option>
<option value="726">Kottayam</option>
<option value="727">Kozhikode</option>
<option value="948">Krishnagiri</option>
<option value="1122">Krishnanagar</option>
<option value="1118">Kunthi</option>
<option value="482">Kurnool</option>
<option value="644">Kurukshetra</option>
<option value="1046">Kushi Nagar</option>
<option value="659">Ladakh</option>
<option value="523">Lakhimpur</option>
<option value="745">Lakshadweep</option>
<option value="1047">Lalganj</option>
<option value="806">Latur</option>
<option value="671">Lohardaga</option>
<option value="1048">Lucknow</option>
<option value="895">Ludhiana</option>
<option value="1049">Machhlishahr</option>
<option value="483">Machilipatnam</option>
<option value="807">Madha</option>
<option value="552">Madhepura</option>
<option value="553">Madhubani</option>
<option value="952">Madurai</option>
<option value="484">Mahabubabad</option>
<option value="554">Maharajganj</option>
<option value="587">Mahasamund</option>
<option value="485">Mahbubnagar</option>
<option value="625">Mahesana</option>
<option value="1050">Mainpuri</option>
<option value="728">Malappuram</option>
<option value="1124">Maldaha Dakshin</option>
<option value="1125">Maldaha Uttar</option>
<option value="486">Malkajgiri</option>
<option value="653">Mandi</option>
<option value="763">Mandla</option>
<option value="764">Mandsour</option>
<option value="702">Mandya</option>
<option value="524">Mangaldoi</option>
<option value="1051">Mathura</option>
<option value="1126">Mathurapur</option>
<option value="809">Maval</option>
<option value="730">Mavelikara</option>
<option value="953">Mayiladuthurai</option>
<option value="875">Mayurbhanj</option>
<option value="487">Medak</option>
<option value="1127">Medinipur</option>
<option value="1052">Meerut</option>
<option value="1053">Mirzapur</option>
<option value="1054">Misrikh</option>
<option value="846">Mizoram</option>
<option value="1055">Mohanlalganj</option>
<option value="1056">Moradabad</option>
<option value="765">Morena</option>
<option value="810">Mumbai North</option>
<option value="811">Mumbai North Central</option>
<option value="812">Mumbai North East</option>
<option value="813">Mumbai North West</option>
<option value="814">Mumbai South</option>
<option value="815">Mumbai South Central</option>
<option value="557">Munger</option>
<option value="1129">Murshidabad</option>
<option value="1057">Muzaffarnagar</option>
<option value="558">Muzaffarpur</option>
<option value="704">Mysore</option>
<option value="876">Nabarangpur</option>
<option value="847">Nagaland</option>
<option value="954">Nagapattinam</option>
<option value="489">Nagarkurnool</option>
<option value="922">Nagaur</option>
<option value="1058">Nagina</option>
<option value="816">Nagpur</option>
<option value="1082">Nainital Udhamsingh Nagar</option>
<option value="559">Nalanda</option>
<option value="490">Nalgonda</option>
<option value="956">Namakkal</option>
<option value="817">Nanded</option>
<option value="818">Nandurbar</option>
<option value="491">Nandyal</option>
<option value="493">Narasaraopet</option>
<option value="494">Narsapuram</option>
<option value="819">Nashik</option>
<option value="627">Navsari</option>
<option value="560">Nawada</option>
<option value="495">Nellore</option>
<option value="852">New Delhi</option>
<option value="957">Nilgiris</option>
<option value="496">Nizamabad</option>
<option value="853">North East Delhi</option>
<option value="597">North Goa</option>
<option value="854">North West Delhi</option>
<option value="525">Nowgong</option>
<option value="497">Ongole</option>
<option value="820">Osmanabad</option>
<option value="843">Outer Manipur</option>
<option value="734">Palakkad</option>
<option value="672">Palamu</option>
<option value="958">Palani</option>
<option value="821">Palghar</option>
<option value="923">Pali</option>
<option value="628">Panchmahal</option>
<option value="823">Parbhani</option>
<option value="561">Paschim Champaran</option>
<option value="562">Pataliputra</option>
<option value="629">Patan</option>
<option value="736">Pathanamthitta</option>
<option value="896">Patiala</option>
<option value="564">Patna Sahib</option>
<option value="499">Peddapalli</option>
<option value="959">Perambalur</option>
<option value="1060">Phulpur</option>
<option value="1061">Pilibhit</option>
<option value="961">Pollachi</option>
<option value="737">Ponnani</option>
<option value="630">Porbandar</option>
<option value="1062">Pratapgarh</option>
<option value="882">Puducherry</option>
<option value="824">Pune</option>
<option value="879">Puri</option>
<option value="565">Purnia</option>
<option value="1132">Purulia</option>
<option value="566">Purvi Champaran</option>
<option value="1063">Rae Bareli</option>
<option value="705">Raichur</option>
<option value="825">Raigad</option>
<option value="1133">Raiganj</option>
<option value="588">Raigarh</option>
<option value="589">Raipur</option>
<option value="500">Rajahmundry</option>
<option value="501">Rajampet</option>
<option value="766">Rajgarh</option>
<option value="631">Rajkot</option>
<option value="673">Rajmahal</option>
<option value="590">Rajnandgaon</option>
<option value="924">Rajsamand</option>
<option value="963">Ramanathapuram</option>
<option value="1064">Rampur</option>
<option value="827">Ramtek</option>
<option value="1134">Ranaghat</option>
<option value="674">Ranchi</option>
<option value="767">Ratlam</option>
<option value="829">Ratnagiri Sindhudurg</option>
<option value="830">Raver</option>
<option value="768">Rewa</option>
<option value="1065">Robertsganj</option>
<option value="646">Rohtak</option>
<option value="632">Sabarkantha</option>
<option value="769">Sagar</option>
<option value="1066">Saharanpur</option>
<option value="965">Salem</option>
<option value="1068">Salempur</option>
<option value="569">Samastipur</option>
<option value="880">Sambalpur</option>
<option value="1069">Sambhal</option>
<option value="831">Sangli</option>
<option value="899">Sangrur</option>
<option value="1070">Sant Kabir Nagar</option>
<option value="570">Saran</option>
<option value="592">Sarguja</option>
<option value="571">Sasaram</option>
<option value="832">Satara</option>
<option value="770">Satna</option>
<option value="502">Secunderabad</option>
<option value="772">Shahdol</option>
<option value="1072">Shahjahanpur</option>
<option value="572">Sheohar</option>
<option value="844">Shillong</option>
<option value="654">Shimla</option>
<option value="706">Shimoga</option>
<option value="833">Shirdi</option>
<option value="834">Shirur</option>
<option value="835">Sholapur</option>
<option value="1073">Shrawasti</option>
<option value="774">Sidhi</option>
<option value="927">Sikar</option>
<option value="930">Sikkim</option>
<option value="526">Silchar</option>
<option value="675">Singhbhum</option>
<option value="647">Sirsa</option>
<option value="573">Sitamarhi</option>
<option value="1074">Sitapur</option>
<option value="966">Sivaganga</option>
<option value="574">Siwan</option>
<option value="836">Solapur</option>
<option value="648">Sonepat</option>
<option value="649">Sonipat</option>
<option value="856">South Delhi</option>
<option value="599">South Goa</option>
<option value="1136">Sreerampur</option>
<option value="504">Srikakulam</option>
<option value="660">Srinagar</option>
<option value="968">Sriperumbudur</option>
<option value="1075">Sultanpur</option>
<option value="881">Sundargarh</option>
<option value="575">Supaul</option>
<option value="633">Surat</option>
<option value="634">Surendranagar</option>
<option value="593">Surguja</option>
<option value="1137">Tamluk</option>
<option value="1083">Tehri Garhwal</option>
<option value="969">Tenkasi</option>
<option value="527">Tezpur</option>
<option value="837">Thane</option>
<option value="970">Thanjavur</option>
<option value="971">Theni</option>
<option value="739">Thiruvananthapuram</option>
<option value="972">Thoothukkudi</option>
<option value="740">Thrissur</option>
<option value="775">Tikamgarh</option>
<option value="976">Tiruchirappalli</option>
<option value="977">Tirunelveli</option>
<option value="506">Tirupati</option>
<option value="979">Tiruppur</option>
<option value="980">Tiruvallur</option>
<option value="981">Tiruvannamalai</option>
<option value="40707">Tonk Sawai Madhopur</option>
<option value="986">Tripura East</option>
<option value="987">Tripura West</option>
<option value="707">Tumkur</option>
<option value="845">Tura</option>
<option value="929">Udaipur</option>
<option value="661">Udhampur</option>
<option value="709">Udupi Chikmagalur</option>
<option value="576">Ujiarpur</option>
<option value="776">Ujjain</option>
<option value="1138">Uluberia</option>
<option value="1076">Unnao</option>
<option value="710">Uttara Kannada</option>
<option value="743">Vadakara</option>
<option value="635">Vadodara</option>
<option value="577">Vaishali</option>
<option value="578">Valmiki Nagar</option>
<option value="636">Valsad</option>
<option value="1077">Varanasi</option>
<option value="983">Vellore</option>
<option value="777">Vidisha</option>
<option value="507">Vijayawada</option>
<option value="984">Viluppuram</option>
<option value="985">Virudhunagar</option>
<option value="508">Visakhapatnam</option>
<option value="509">Vizianagaram</option>
<option value="510">Warangal</option>
<option value="838">Wardha</option>
<option value="744">Wayanad</option>
<option value="857">West Delhi</option>
<option value="841">Yavatmal Washim</option>
<option value="511">Zahirabad</option>

</select>
<div id="alertMessage_cons_Himachal Pradesh"></div>

<div class="view-results"><a onclick="navigateToConstituencyPageFrmSpeclPge('constituency_parliament','alertMessage_cons_Himachal Pradesh')" href="javascript:{}">view constituency</a></div>
</div>

