<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>



<div class="selectHeading">
	<span class="selectDivStyle">Rajasthan Districts</span>
	<span style="margin-left: 5px;">Know About Your District</span>
	<select class="selectBoxWidth" id="districtList_Himachal Pradesh" name="district">
	<option value="0">Select District</option>
   <option value="343">Ganganagar	</option>	
	<option value="344">Hanumangarh	</option>	
	<option value="345">Bikaner	</option>	
	<option value="346">Churu	</option>	
	<option value="347">Jhunjhunun	</option>	
	<option value="348">Alwar	</option>	
	<option value="349">Bharatpur	</option>	
	<option value="350">Dhaulpur	</option>	
	<option value="351">Karauli	</option>	
	<option value="352">Sawai Madhopur	</option>	
	<option value="353">Dausa	</option>	
	<option value="354">Jaipur	</option>	
	<option value="355">Sikar	</option>	
	<option value="356">Nagaur	</option>	
	<option value="357">Jodhpur	</option>	
	<option value="358">Jaisalmer	</option>	
	<option value="359">Barmer	</option>	
	<option value="360">Jalor	</option>	
	<option value="361">Sirohi	</option>	
	<option value="362">Pali	</option>	
	<option value="363">Ajmer	</option>	
	<option value="364">Tonk	</option>	
	<option value="365">Bundi	</option>	
	<option value="366">Bhilwara	</option>	
	<option value="367">Rajsamand	</option>	
	<option value="368">Udaipur	</option>	
	<option value="369">Dungarpur	</option>	
	<option value="370">Banswara	</option>	
	<option value="371">Chittaurgarh	</option>	
	<option value="372">Kota	</option>	
	<option value="373">Baran	</option>	
	<option value="374">Jhalawar	</option>	
   </select>
   <div id="alertMessage_dist_Himachal Pradesh"></div>

	<div class="view-results"><a onclick="navigateToDistrictPageFrmSpeclPge('districtList_Himachal Pradesh','alertMessage_dist_Himachal Pradesh')" href="javascript:{}">view results</a></div>


</div>
<div class="selectHeading">
	<span class="selectDivStyle">Rajasthan Constituencies </span>
	<span style="margin-left: 12px;">Know About Your Assembly Constituency</span>
<select class="selectBoxWidth" id="constituency_Himachal Pradesh" name="constituency">
<option value="0">Select Constituency</option>
<option value="	40456">Sadulshahar</option>
	<option value="	40457">Ganganagar</option>
	<option value="	40458">Karanpur</option>
	<option value="	40459">Suratgarh</option>
	<option value="	40460">Raisinghnagar</option>
	<option value="	40461">Anupgarh</option>
	<option value="	40462">Sangaria</option>
	<option value="	40463">Hanumangarh</option>
	<option value="	40464">Pilibanga</option>
	<option value="	40465">Nohar</option>
	<option value="	40466">Bhadra</option>
	<option value="	40467">Khajuwala</option>
	<option value="	40468">Bikaner West</option>
	<option value="	40469">Bikaner East</option>
	<option value="	40470">Kolayat</option>
	<option value="	40471">Lunkaransar</option>
	<option value="	40472">Dungargarh</option>
	<option value="	40473">Nokha</option>
	<option value="	40474">Sadulpur</option>
	<option value="	40475">Taranagar</option>
	<option value="	40476">Sardarshahar</option>
	<option value="	40477">Churu</option>
	<option value="	40478">Ratangarh</option>
	<option value="	40479">Sujangarh</option>
	<option value="	40480">Pilani</option>
	<option value="	40481">Surajgarh</option>
	<option value="	40482">Jhunjhunu</option>
	<option value="	40483">Mandawa</option>
	<option value="	40484">Nawalgarh</option>
	<option value="	40485">Udaipurwati</option>
	<option value="	40486">Khetri</option>
	<option value="	40487">Fatehpur</option>
	<option value="	40488">LACHMANGARH</option>
	<option value="	40489">Dhod</option>
	<option value="	40490">Sikar</option>
	<option value="	40491">DantaRamgarh</option>
	<option value="	40492">Khandela</option>
	<option value="	40493">Neem Ka Thana</option>
	<option value="	40494">Srimadhopur</option>
	<option value="	40495">Kotputli</option>
	<option value="	40496">Viratnagar</option>
	<option value="	40497">Shahpura</option>
	<option value="	40498">Chomu</option>
	<option value="	40499">Phulera</option>
	<option value="	40500">Dudu</option>
	<option value="	40501">Jhotwara</option>
	<option value="	40502">Amber</option>
	<option value="	40503">Jamwa Ramgarh</option>
	<option value="	40504">HawaMahal</option>
	<option value="	40505">Vidhyadhar Nagar</option>
	<option value="	40506">Civil Lines</option>
	<option value="	40507">KishanPole</option>
	<option value="	40508">Adarsh Nagar</option>
	<option value="	40509">Malviya Nagar</option>
	<option value="	40510">Sanganer</option>
	<option value="	40511">Bagru</option>
	<option value="	40512">Bassi</option>
	<option value="	40513">Chaksu</option>
	<option value="	40514">Tijara</option>
	<option value="	40515">Kishangarh Bas</option>
	<option value="	40516">Mundawar</option>
	<option value="	40517">Behror</option>
	<option value="	40518">Bansur</option>
	<option value="	40519">Thanagazi</option>
	<option value="	40520">Alwar Rural</option>
	<option value="	40521">Alwar Urban</option>
	<option value="	40522">Ramgarh</option>
	<option value="	40523">Rajgarh Laxmangarh</option>
	<option value="	40524">Kathumar</option>
	<option value="	40525">Kaman</option>
	<option value="	40526">Nagar</option>
	<option value="	40527">Deeg Kumher</option>
	<option value="	40528">Bharatpur</option>
	<option value="	40529">Nadbai</option>
	<option value="	40530">Weir</option>
	<option value="	40531">Bayana</option>
	<option value="	40532">Baseri</option>
	<option value="	40533">Bari</option>
	<option value="	40534">Dholpur</option>
	<option value="	40535">Rajakhera</option>
	<option value="	40536">Todabhim</option>
	<option value="	40537">Hindaun</option>
	<option value="	40538">Karauli</option>
	<option value="	40539">Sapotra</option>
	<option value="	40540">Bandikui</option>
	<option value="	40541">Mahuwa</option>
	<option value="	40542">Sikrai</option>
	<option value="	40543">Dausa</option>
	<option value="	40544">Lalsot</option>
	<option value="	40545">Gangapur</option>
	<option value="	40546">Bamanwas</option>
	<option value="	40547">Sawai Madhopur</option>
	<option value="	40548">Khandar</option>
	<option value="	40549">Malpura</option>
	<option value="	40550">Niwai</option>
	<option value="	40551">Tonk</option>
	<option value="	40552">Deoli Uniara</option>
	<option value="	40553">Kishangarh</option>
	<option value="	40554">Pushkar</option>
	<option value="	40555">Ajmer North</option>
	<option value="	40556">Ajmer South</option>
	<option value="	40557">Nasirabad</option>
	<option value="	40558">Beawar</option>
	<option value="	40559">Masuda</option>
	<option value="	40560">Kekri</option>
	<option value="	40561">Ladnun</option>
	<option value="	40562">Deedwana</option>
	<option value="	40563">Jayal</option>
	<option value="	40564">Nagaur</option>
	<option value="	40565">Khinwsar</option>
	<option value="	40566">Merta</option>
	<option value="	40567">Degana</option>
	<option value="	40568">Makrana</option>
	<option value="	40569">Parbatsar</option>
	<option value="	40570">Nawan</option>
	<option value="	40571">Jaitaran</option>
	<option value="	40572">Sojat</option>
	<option value="	40573">Pali</option>
	<option value="	40574">Marwar Junction</option>
	<option value="	40575">Bali</option>
	<option value="	40576">Sumerpur</option>
	<option value="	40577">Phalodi</option>
	<option value="	40578">Lohawat</option>
	<option value="	40579">Shergarh</option>
	<option value="	40580">Osian</option>
	<option value="	40581">Bhopalgarh</option>
	<option value="	40582">Sardarpura</option>
	<option value="	40583">Jodhpur</option>
	<option value="	40584">Soorsagar</option>
	<option value="	40585">Luni</option>
	<option value="	40586">Bilara</option>
	<option value="	40587">Jaisalmer</option>
	<option value="	40588">Pokaran</option>
	<option value="	40589">Sheo</option>
	<option value="	40590">Barmer</option>
	<option value="	40591">Baytoo</option>
	<option value="	40592">Pachpadra</option>
	<option value="	40593">Siwana</option>
	<option value="	40594">Gudha Malani</option>
	<option value="	40595">Chohtan</option>
	<option value="	40596">Ahore</option>
	<option value="	40597">Jalore</option>
	<option value="	40598">Bhinmal</option>
	<option value="	40599">Sanchore</option>
	<option value="	40600">Raniwara</option>
	<option value="	40601">Sirohi</option>
	<option value="	40602">Pindwara Abu</option>
	<option value="	40603">Reodar</option>
	<option value="	40604">Gogunda</option>
	<option value="	40605">Jhadol</option>
	<option value="	40606">Kherwara</option>
	<option value="	40607">Udaipur Rural</option>
	<option value="	40608">Udaipur</option>
	<option value="	40609">Mavli</option>
	<option value="	40610">Vallabhnagar</option>
	<option value="	40611">Salumber</option>
	<option value="	40612">Dhariawad</option>
	<option value="	40613">Dungarpur</option>
	<option value="	40614">Aspur</option>
	<option value="	40615">Sagwara</option>
	<option value="	40616">Chorasi</option>
	<option value="	40617">GHATOL</option>
	<option value="	40618">Garhi</option>
	<option value="	40619">Banswara</option>
	<option value="	40620">Bagidora</option>
	<option value="	40621">Kushalgarh</option>
	<option value="	40622">Kapasan</option>
	<option value="	40623">Begun</option>
	<option value="	40624">Chittorgarh</option>
	<option value="	40625">Nimbahera</option>
	<option value="	40626">Bari Sadri</option>
	<option value="	40627">Pratapgarh</option>
	<option value="	40628">Bhim</option>
	<option value="	40629">Kumbhalgarh</option>
	<option value="	40630">Rajsamand</option>
	<option value="	40631">Nathdwara</option>
	<option value="	40632">Asind</option>
	<option value="	40633">Mandal</option>
	<option value="	40634">Sahara</option>
	<option value="	40635">Bhilwara</option>
	<option value="	40636">Shahpura</option>
	<option value="	40637">Jahazpur</option>
	<option value="	40638">Mandalgarh</option>
	<option value="	40639">Hindoli</option>
	<option value="	40640">Keshoraipatan</option>
	<option value="	40641">Bundi</option>
	<option value="	40642">Pipalda</option>
	<option value="	40643">Sangod</option>
	<option value="	40644">Kota North</option>
	<option value="	40645">Kota South</option>
	<option value="	40646">Ladpura</option>
	<option value="	40647">Ramganj Mandi</option>
	<option value="	40648">Anta</option>
	<option value="	40649">Kishanganj</option>
	<option value="	40650">Baran Atru</option>
	<option value="	40651">Chhabra</option>
	<option value="	40652">Dag</option>
	<option value="	40653">Jhalrapatan</option>
	<option value="	40654">Khanpur</option>
	<option value="	40655">Manohar Thana</option>
</select>
<div id="alertMessage_cons_Himachal Pradesh"></div>

<div class="view-results"><a onclick="navigateToConstituencyPageFrmSpeclPge('constituency_Himachal Pradesh','alertMessage_cons_Himachal Pradesh')" href="javascript:{}">view constituency</a></div>
</div>

