INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ADILABAD', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ASIFABAD', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BELLAMPALLE', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BOATH', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHENNUR', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KHANAPUR', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MANCHERIAL', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MUDHOLE', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NIRMAL', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SIRPUR', 2, null, null, 1, 1, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ANANTAPUR', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ANANTAPUR URBAN', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DHARMAVARAM', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GOOTY', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GORANTLA', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GUNTAKAL', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'HINDUPUR', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KADIRI', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KALYANDURG', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MADAKASIRA', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NALLAMADA', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PENUKONDA', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PUTTAPARTHI', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAPTADU', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAYADURG', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SINGANAMALA', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TADPATRI', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'URAVAKONDA', 2, null, null, 1, 22, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHANDRAGIRI', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHITTOOR', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'Gangadhara Nellore', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KUPPAM', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MADANAPALLE', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NAGARI', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'Palamaner', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PILERU', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PUNGANUR', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PUTHALAPATTU', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PUTTUR', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SATYAVEDU', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SRIKALAHASTI', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SULURPET', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'THAMBALLAPALLE', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TIRUPATI', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VEPANJERI', 2, null, null, 1, 23, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BADVEL', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'Kadapa', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'JAMMALAMADUGU', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KAMALAPURAM', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KODUR', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'LAKKIREDDIPALLI', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MADANPALLE', 2, null, null, 1, 20, 1)
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MYDUKUR', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PRODDATUR', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'Pulivendla', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAJAMPET', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAYACHOTY', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VAYALPAD', 2, null, null, 1, 20, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ALLAVARAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'Amalapuram', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAYACHOTY', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ANAPARTHY', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BURUGUPUDI', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GANNAVARAM-EG', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'JAGGAMPETA', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KADIAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KAKINADA', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KAKINADA CITY', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KAKINADA RURAL', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KOTHAPETA', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MANDAPETA', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MUMMIDIVARAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NAGARAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PEDDAPURAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PITHAPURAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PRATHIPADU', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAJAHMUNDRY', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAJAHMUNDRY CITY', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAJAHMUNDRY RURAL', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAJANAGARAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAMACHANDRAPURAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAMPACHODAVARAM', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAZOLE', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SAMPARA', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TALLAREVU', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TUNI', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BAPATLA', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHILAKALURIPET', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DUGGIRALA', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GUNTUR EAST', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GUNTUR WEST', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GUNTUR[I]', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GUNTUR[II]', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GURZALA', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KUCHINAPUDI', 2, null, null, 1, 17, 1)
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MACHERLA', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MANGALAGIRI', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MARTUR', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARASARAOPET', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NIDUMOLU', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PEDDAKURAPADU', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PONNUR', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PRATHIPAD', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'REPALLE', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SATTENAPALLI', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TADIKONDA', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TENALI', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VEMURU', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VINUKONDA', 2, null, null, 1, 17, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'AMBERPET', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ASAFNAGAR', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BAHADURPURA', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHANDRAYANGUTTA', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHARMINAR', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GOSHAMAHAL', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'HIMAYATNAGAR', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'JUBILEE HILLS', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KARWAN', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KHAIRATABAD', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MAHARAJGUNJ', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MALAKPET', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MUSHEERABAD', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NAMPALLY', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SANATHNAGAR', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SECUNDERABAD', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SECUNDERABAD CANTONMENT', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'YAKUTPURA', 2, null, null, 1, 5, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BUGGARAM', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHINNUR', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHOPPADANDI', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DHARMAPURI', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'HUSNABAD', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'HUZURABAD', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'INDURTHI', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'JAGTIAL', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KARIMNAGAR', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KORATLA', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'LUXETTIPET', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MANAKONDUR', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MANTHANI', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'METPALLI', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MYDARAM', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARELLA', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PEDDAPALLI', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAMAGUNDAM', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SIRCILLA', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VEMULAWADA', 2, null, null, 1, 3, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ASWARAOPETA', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BHADRACHALAM', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BURGAMPAHAD', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHINTAPALLI', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KHAMMAM', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KOTHAGUDEM', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MADHIRA', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PALAIR', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PINAPAKA', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SATHUPALLI', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SHUJATNAGAR', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'WYRA', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'YELLANDU', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'YELLAVARAM', 2, null, null, 1, 10, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'AVANIGADDA', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BANDAR', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GANNAVARAM', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GUDIVADA', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'JAGGAYYAPET', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KAIKALUR', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KANKIPADU', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MACHILIPATNAM', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MALLESWARAM', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MUDINEPALLI', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MYLAVARAM', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NANDIGAMA', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NUZVID', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PAMARRU', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PEDANA', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PENAMALURU', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TIRUVURU', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VIJAYAWADA CENTRAL', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VIJAYAWADA EAST', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VIJAYAWADA WEST', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VUYYUR', 2, null, null, 1, 16, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ADONI', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ALLAGADDA', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ALUR', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ATMAKUR', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BANAGANAPALLE', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DHONE', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KODUMUR', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KOILKUNTLA', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KURNOOL', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MANTRALAYAM', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NANDIKOTKUR', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NANDYAL', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PANYAM', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PATTIKONDA', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SRISAILAM', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'YEMMIGANUR', 2, null, null, 1, 21, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ACHAMPET', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ALAMPUR', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'AMARCHINTA', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DEVARKADRA', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GADWAL', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'JADCHERLA', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KALWAKURTHI', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KODANGAL', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KOLLAPUR', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MAHBUBNAGAR', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MAKTHAL', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NAGARKURNOOL', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARAYANPET', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SHADNAGAR', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'WANAPARTHY', 2, null, null, 1, 7, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ANDOLE', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DOMMAT', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DUBBAK', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GAJWEL', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MEDAK', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARAYANKHED', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARSAPUR', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PATANCHERU', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAMAYAMPET', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SANGAREDDY', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SIDDIPET', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ZAHIRABAD', 2, null, null, 1, 4, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ALAIR', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BHONGIR', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHALAKURTHI', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DEVERKONDA', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'HUZURNAGAR', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KODAD', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MIRYALGUDA', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MUNGODE', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NAGARJUNA SAGAR', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NAKREKAL', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NALGONDA', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAMANNAPET', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SURYAPET', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TUNGATURTHI', 2, null, null, 1, 8, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ALLUR', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ATMAKUR-NELLORE', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GUDUR', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KAVALI', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KOVUR', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NELLORE', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NELLORE CITY', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NELLORE RURAL', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAPUR', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SARVEPALLI', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SULLURPET', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'UDAYAGIRI', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VENKATAGIRI', 2, null, null, 1, 19, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ARMOOR', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BALKONDA', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BANSWADA', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BODHAN', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DICHPALLI', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'JUKKAL', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KAMAREDDY', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NIZAMABAD', 2, null, null, 1, 2, 1)
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NIZAMABAD [RURAL]', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NIZAMABAD [URBAN]', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'YELLAREDDY', 2, null, null, 1, 2, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ADDANKI', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHIRALA', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CUMBUM', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DARSI', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GIDDALUR', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KANDUKUR', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KANIGIRI', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KONDEPI', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MARKAPUR', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ONGOLE', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PARCHUR', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SANTHANUTHALAPADU', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'YERRAGONDAPALEM', 2, null, null, 1, 18, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHEVELLA', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'IBRAHIMPATNAM', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KUKATPALLE', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'LAL BAHADUR NAGAR', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MAHESWARAM', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MALKAJGIRI', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MEDCHAL', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PARGI', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'QUTBULLAPUR', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAJENDRANAGAR', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SERILINGAMPALLY', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TANDUR', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'UPPAL', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VICARABAD', 2, null, null, 1, 6, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'AMADALAVALASA', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ETCHERLA', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'HARISCHANDRAPURAM', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ICHAPURAM', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARASANNAPETA', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PALAKONDA', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PALASA', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PATHAPATNAM', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'RAJAM', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SOMPETA', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SRIKAKULAM', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TEKKALI', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ANAKAPALLI', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ARAKU VALLEY', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BHEEMUNIPATNAM', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BHIMLI', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BHOGAPURAM', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHODAVARAM', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ELAMANCHILI', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GAJUWAKA', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MADUGULA', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARSIPATNAM', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PADERU', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PARAVADA', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PAYAKARAOPETA', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PENDURTHI', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'UTTARAPALLI', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VISAKHAPATNAM EAST', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VISAKHAPATNAM NORTH', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VISAKHAPATNAM SOUTH', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VISAKHAPATNAM WEST', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VISAKHAPATNAM[I]', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VISAKHAPATNAM[II]', 2, null, null, 1, 13, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BOBBILI', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHEEPURUPALLI', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GAJAPATHINAGARAM', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KOTHURU', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KURUPAM', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NAGURU', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NELLIMARLA', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PARVATHIPURAM', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SALUR', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SATHIVADA', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SRUNGAVARAPUKOTA', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'THERLAM', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'UNUKURU', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VIZIANAGARAM', 2, null, null, 1, 12, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BHUPALPALLE', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHERIYAL', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DORNAKAL', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GHANPUR', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'HANAMKONDA', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'JANGAON', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KAMALAPUR', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MAHBUBABAD', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'MULUG', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARSAMPET', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PALAKURTHI', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PARKAL', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SHYAMPET', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'WARANGAL', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'WARANGAL EAST', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'WARANGAL WEST', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'WARDHANNAPET', 2, null, null, 1, 9, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ACHANTA', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ATTILI', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'BHIMAVARAM', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'CHINTALAPUDI', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'DENDULUR', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ELURU', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'GOPALPURAM', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'KOVVUR', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NARASAPUR', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'NIDADAVOLE', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PALACOLE', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'PENUGONDA', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'POLAVARAM', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TADEPALLIGUDEM', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'TANUKU', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'UNDI', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'UNGUTUR', 2, null, null, 1, 15, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'VUNUKURU', 2, null, null, 1, 11, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'ALAMURU', 2, null, null, 1, 14, 1) 
GO
INSERT INTO constituency(name, election_scope_id, start_date, deform_date, state_id, district_id, country_id)    VALUES( 'SOMPARA', 2, '1989-05-20', '1994-01-05', 1, 14, 1) 
GO

insert into constituency_tehsil(constituency_id,tehsil_id,complete_tehsil) values ((select constituency_id from constituency where name='KAVALI'),835,TRUE)
GO
insert into constituency_tehsil(constituency_id,tehsil_id,complete_tehsil) values ((select constituency_id from constituency where name='KAVALI'),843,TRUE)
GO
insert into constituency_tehsil(constituency_id,tehsil_id,complete_tehsil) values ((select constituency_id from constituency where name='KAVALI'),844,TRUE)
GO
insert into constituency_tehsil(constituency_id,tehsil_id,complete_tehsil) values ((select constituency_id from constituency where name='KAVALI'),836,TRUE)
GO
