/*
Script generated by Aqua Data Studio 7.5.11 on Jul-09-2009 01:17:36 AM
Database: null
Schema: <All Schemas>
*/

ALTER TABLE nomination
	DROP FOREIGN KEY fk_candidate_nomination
GO

ALTER TABLE constituency_election
	DROP FOREIGN KEY fk_constituency_constituency_election
GO

ALTER TABLE nomination
	DROP FOREIGN KEY fk_constituency_election_nomination
GO

ALTER TABLE constituency_election_result
	DROP FOREIGN KEY fk_constituency_election_constituency_election_result
GO

ALTER TABLE state
	DROP FOREIGN KEY fk_country_state
GO

ALTER TABLE constituency
	DROP FOREIGN KEY fk_district_constituency
GO

ALTER TABLE tehsil
	DROP FOREIGN KEY fk_district_mandal
GO

ALTER TABLE constituency_election
	DROP FOREIGN KEY fk_election_constituency_election
GO

ALTER TABLE election
	DROP FOREIGN KEY fk_election_scope_election
GO

ALTER TABLE constituency
	DROP FOREIGN KEY fk_election_scope_constituency
GO

ALTER TABLE election_scope
	DROP FOREIGN KEY fk_election_type_election_scope
GO

ALTER TABLE candidate_result
	DROP FOREIGN KEY fk_nomination_candidate_result
GO

ALTER TABLE nomination
	DROP FOREIGN KEY fk_party_nomination
GO

ALTER TABLE constituency
	DROP FOREIGN KEY fk_state_constituency
GO

ALTER TABLE district
	DROP FOREIGN KEY fk_state_district
GO

ALTER TABLE township
	DROP FOREIGN KEY fk_tehsil_township
GO

ALTER TABLE ward
	DROP FOREIGN KEY fk_township_ward
GO

DROP TABLE candidate
GO

DROP TABLE candidate_result
GO

DROP TABLE constituency
GO

DROP TABLE constituency_election
GO

DROP TABLE constituency_election_result
GO

DROP TABLE country
GO

DROP TABLE district
GO

DROP TABLE election
GO

DROP TABLE election_scope
GO

DROP TABLE election_type
GO

DROP TABLE nomination
GO

DROP TABLE party
GO

DROP TABLE state
GO

DROP TABLE tehsil
GO

DROP TABLE township
GO

DROP TABLE ward
GO

CREATE TABLE candidate ( 
	candidate_id 	bigint(15) NOT NULL,
	firstname    	varchar(40) NULL,
	middlename   	varchar(40) NULL,
	lastname     	varchar(40) NULL,
	dateofbirth  	date NULL,
	email_address	varchar(60) NULL,
	phone        	varchar(25) NULL,
	mobile       	varchar(25) NULL,
	address      	varchar(25) NULL,
	education    	varchar(25) NULL,
	gender       	varchar(25) NULL,
	PRIMARY KEY(candidate_id)
)
GO

CREATE TABLE candidate_result ( 
	candidate_result_id	bigint(15) NOT NULL,
	nomination_id      	bigint(15) NULL,
	votes_earned       	double(10,0) NULL,
	PRIMARY KEY(candidate_result_id)
)
GO

CREATE TABLE constituency ( 
	constituency_id  	bigint(15) NOT NULL,
	name             	varchar(50) NULL,
	election_scope_id	bigint(15) NULL,
	start_date       	date NULL,
	deform_date      	date NULL,
	state_id         	bigint(15) NULL,
	district_id      	bigint(15) NULL,
	country_id       	bigint(15) NULL,
	PRIMARY KEY(constituency_id)
)
GO

CREATE TABLE constituency_election ( 
	consti_elec_id 	bigint(15) NOT NULL,
	constituency_id	bigint(15) NULL,
	election_id    	bigint(15) NULL,
	election_date  	date NULL,
	PRIMARY KEY(consti_elec_id)
)
GO

CREATE TABLE constituency_election_result ( 
	consti_elec_result_id	bigint(15) NOT NULL,
	total_votes          	double(10,0) NULL,
	valid_votes          	double(10,0) NULL,
	rejected_votes       	double(10,0) NULL,
	missing_votes        	double(10,0) NULL,
	total_votes_polled   	double(10,0) NULL,
	tendered_votes       	double(10,0) NULL,
	consti_elec_id       	bigint(15) NULL,
	PRIMARY KEY(consti_elec_result_id)
)
GO

CREATE TABLE country ( 
	country_id  	bigint(15) NOT NULL,
	country_name	varchar(100) NOT NULL,
	capital     	varchar(100) NULL,
	iso_code    	varchar(25) NULL,
	PRIMARY KEY(country_id)
)
GO

CREATE TABLE district ( 
	district_id     	bigint(15) NOT NULL,
	district_name   	varchar(100) NULL,
	district_capital	varchar(100) NULL,
	area            	decimal(15,5) NULL,
	population      	double(10,0) NULL,
	state_id        	bigint(15) NULL,
	district_code   	bigint(15) NULL,
	start_date      	date NULL,
	deform_date     	date NULL,
	PRIMARY KEY(district_id)
)
GO

CREATE TABLE election ( 
	election_id      	bigint(15) NOT NULL,
	election_scope_id	bigint(15) NULL,
	notification_date	date NULL,
	start_date       	date NULL,
	end_date         	varchar(25) NULL,
	election_year    	varchar(25) NULL,
	PRIMARY KEY(election_id)
)
GO

CREATE TABLE election_scope ( 
	election_socpe_id	bigint(15) NOT NULL,
	election_type_id 	bigint(15) NULL,
	country_state_id 	bigint(15) COMMENT 'If the election_type_id = 1 then country_state_id = country_id else country_state_id = state_id'  NULL,
	PRIMARY KEY(election_socpe_id)
)
GO

CREATE TABLE election_type ( 
	election_type_id	bigint(15) NOT NULL,
	election_type   	varchar(25) NULL,
	scope           	varchar(25) NULL,
	PRIMARY KEY(election_type_id)
)
GO

CREATE TABLE nomination ( 
	nomination_id    	bigint(15) NOT NULL,
	candidate_id     	bigint(15) NULL,
	consti_elec_id   	bigint(15) NULL,
	nomination_status	varchar(25) NULL,
	party_id         	bigint(15) NULL,
	assets           	double(10,0) NULL,
	liabilities      	double(10,0) NULL,
	criminal_charges 	varchar(300) NULL,
	PRIMARY KEY(nomination_id)
)
GO

CREATE TABLE party ( 
	party_id           	bigint(15) NOT NULL,
	long_name          	varchar(100) NULL,
	short_name         	varchar(25) NULL,
	symbol             	varchar(25) NULL,
	address            	varchar(300) NULL,
	comments           	varchar(300) NULL,
	party_recognization	varchar(25) NULL,
	PRIMARY KEY(party_id)
)
GO

CREATE TABLE state ( 
	state_id         	bigint(15) NOT NULL,
	state_name       	varchar(100) NOT NULL,
	admin_capital    	varchar(100) NULL,
	legis_capital    	varchar(100) NULL,
	judiciary_capital	varchar(100) NULL,
	year_established 	date NULL,
	state_language   	varchar(50) NULL,
	state_symbol     	varchar(50) NULL,
	state_song       	varchar(50) NULL,
	state_animal     	varchar(50) NULL,
	state_bird       	varchar(50) NULL,
	state_tree       	varchar(50) NULL,
	state_sport      	varchar(50) NULL,
	state_dance      	varchar(50) NULL,
	state_flower     	varchar(50) NULL,
	iso_code         	varchar(25) NULL,
	country_id       	bigint(15) NULL,
	state_code       	bigint(15) NULL,
	start_date       	date NULL,
	deform_date      	date NULL,
	PRIMARY KEY(state_id)
)
GO

CREATE TABLE tehsil ( 
	tehsil_id  	bigint(15) NOT NULL,
	tehsil_name	varchar(100) NULL,
	district_id	bigint(15) NULL,
	tehsil_code	bigint(15) NULL,
	start_date 	date NULL,
	deform_date	varchar(25) NULL,
	PRIMARY KEY(tehsil_id)
)
GO

CREATE TABLE township ( 
	township_id  	bigint(15) NOT NULL,
	township_name	varchar(100) NULL,
	township_code	bigint(15) COMMENT 'township_code is census code for village or town'  NULL,
	tehsil_id    	bigint(15) NULL,
	township_type	varchar(25) COMMENT 'It indicates either it is TOWN or VILLAGE'  NULL,
	PRIMARY KEY(township_id)
)
GO

CREATE TABLE ward ( 
	ward_id    	bigint(15) NOT NULL,
	ward_name  	varchar(100) NULL,
	ward_code  	bigint(15) NULL,
	township_id	bigint(15) NULL,
	PRIMARY KEY(ward_id)
)
GO

ALTER TABLE nomination
	ADD CONSTRAINT fk_candidate_nomination
	FOREIGN KEY(candidate_id)
	REFERENCES candidate(candidate_id)
GO

ALTER TABLE constituency_election
	ADD CONSTRAINT fk_constituency_constituency_election
	FOREIGN KEY(constituency_id)
	REFERENCES constituency(constituency_id)
GO

ALTER TABLE nomination
	ADD CONSTRAINT fk_constituency_election_nomination
	FOREIGN KEY(consti_elec_id)
	REFERENCES constituency_election(consti_elec_id)
GO

ALTER TABLE constituency_election_result
	ADD CONSTRAINT fk_constituency_election_constituency_election_result
	FOREIGN KEY(consti_elec_id)
	REFERENCES constituency_election(consti_elec_id)
GO

ALTER TABLE state
	ADD CONSTRAINT fk_country_state
	FOREIGN KEY(country_id)
	REFERENCES country(country_id)
GO

ALTER TABLE constituency
	ADD CONSTRAINT fk_district_constituency
	FOREIGN KEY(district_id)
	REFERENCES district(district_id)
GO

ALTER TABLE tehsil
	ADD CONSTRAINT fk_district_mandal
	FOREIGN KEY(district_id)
	REFERENCES district(district_id)
GO

ALTER TABLE constituency_election
	ADD CONSTRAINT fk_election_constituency_election
	FOREIGN KEY(election_id)
	REFERENCES election(election_id)
GO

ALTER TABLE election
	ADD CONSTRAINT fk_election_scope_election
	FOREIGN KEY(election_scope_id)
	REFERENCES election_scope(election_socpe_id)
GO

ALTER TABLE constituency
	ADD CONSTRAINT fk_election_scope_constituency
	FOREIGN KEY(election_scope_id)
	REFERENCES election_scope(election_socpe_id)
GO

ALTER TABLE election_scope
	ADD CONSTRAINT fk_election_type_election_scope
	FOREIGN KEY(election_type_id)
	REFERENCES election_type(election_type_id)
GO

ALTER TABLE candidate_result
	ADD CONSTRAINT fk_nomination_candidate_result
	FOREIGN KEY(nomination_id)
	REFERENCES nomination(nomination_id)
GO

ALTER TABLE nomination
	ADD CONSTRAINT fk_party_nomination
	FOREIGN KEY(party_id)
	REFERENCES party(party_id)
GO

ALTER TABLE constituency
	ADD CONSTRAINT fk_state_constituency
	FOREIGN KEY(state_id)
	REFERENCES state(state_id)
GO

ALTER TABLE district
	ADD CONSTRAINT fk_state_district
	FOREIGN KEY(state_id)
	REFERENCES state(state_id)
GO

ALTER TABLE township
	ADD CONSTRAINT fk_tehsil_township
	FOREIGN KEY(tehsil_id)
	REFERENCES tehsil(tehsil_id)
GO

ALTER TABLE ward
	ADD CONSTRAINT fk_township_ward
	FOREIGN KEY(township_id)
	REFERENCES township(township_id)
GO

