package com.itgrids.partyanalyst;

import java.io.File;
import java.util.HashMap;

public class FileNameChange {
	
	public void renameFiles()
	{
		File folder = new File("C:/KAMAL/candidates");
		File[] images = folder.listFiles();
		HashMap<String,Integer> nameMap = getNamesMap();
		for(File image : images)
		{
			String fileName = image.getName().substring(0,image.getName().length()-4);
			Integer candidateId = nameMap.get(fileName);
			System.out.println(nameMap);
			System.out.println(candidateId);
			if(candidateId != null)
			{
				image.renameTo(new File("C:/KAMAL/candidates/"+candidateId.toString()+".jpg"));
				System.out.println(image.getAbsolutePath()+ "-----"+image.getName());
			}
			System.out.println(fileName);
		}
	}
	
	public static void main(String [] args)
	{
		FileNameChange change = new FileNameChange();
		change.renameFiles();
	}
	
	public HashMap<String,Integer> getNamesMap()
	{
		HashMap<String,Integer> namesMap = new HashMap<String, Integer>();
		namesMap.put("A B A GHANI KHAN CHOUDHURY",37449);
		namesMap.put("A K ANTONY",49869);
		namesMap.put("A RAJENDER",3596);
		namesMap.put("A SAMPATH",33027);
		namesMap.put("AARON RASHID J M",35797);
		namesMap.put("ABDUL MANNAN HOSSAIN",37484);
		namesMap.put("ABDULRAHMAN",35864);
		namesMap.put("ABRAHAM V M",914);
		namesMap.put("ACHARIA BASUDEB",37231);
		namesMap.put("ACHARYA NEEMABEN BHAVESHBHAI",187290);
		namesMap.put("ADALA PRABHAKAR REDDY",2812);
		namesMap.put("ADESH PARTAP SINGH",225118);
		namesMap.put("ADESHPARTAP SINGH KAIRON",269961);
		namesMap.put("ADHIKARI SISIR KUMAR",37410);
		namesMap.put("ADHIKARI SUVENDU",37535);
		namesMap.put("ADHIR RANJAN CHOWDHURY",37208);
		namesMap.put("ADI NARAYANA REDDY  CHIDIPIRALLA",2923);
		namesMap.put("ADV P T THOMAS",33062);
		namesMap.put("AHAMADULLA MOHAMMAD  SYED",2874);
		namesMap.put("AHIR (BHARWAD) JETHABHAI GHELABHAI",188109);
		namesMap.put("AHIR VASANBHAI GOPALBHAI",187278);
		namesMap.put("AHIR VIKRAMBHAI ARJANBHAI MADAM",31843);
		namesMap.put("AHMED BIN ABDULLAH BALALA @ AHMED BALALA",635);
		namesMap.put("AJAY MAKAN",34556);
		namesMap.put("AJIT SINGH",36088);
		namesMap.put("AJIT SINGH KOHAR",225157);
		namesMap.put("AKBARUDDIN OWAISI",751);
		namesMap.put("AKHILESH YADAV",36385);
		namesMap.put("ALAGIRI M K",35638);
		namesMap.put("ALE NARENDRA",9277);
		namesMap.put("ALIGIREDDY PRAVEEN REDDY",305);
		namesMap.put("ALIMINETI  UMA MADHAVA REDDY",1079);
		namesMap.put("ALIMINETI MADHAVA REDDY",1086);
		namesMap.put("ALLA KALI  KRISHNA SRINIVAS (ALLA NANI)",2073);
		namesMap.put("ALLETI MAHESHWAR REDDY",78);
		namesMap.put("ALLU ARAVIND",30395);
		namesMap.put("AMANCHI  KRISHNA MOHAN",2627);
		namesMap.put("Amanchi Krishna Mohan",63490);
		namesMap.put("AMARANATH REDDY  AKEPATI",2862);
		namesMap.put("AMARANATHA REDDY N",3412);
		namesMap.put("AMARINDER SINGH",225360);
		namesMap.put("AMBATI  BRAHMANAIAH",2201);
		namesMap.put("AMBICA BANERJEE",37354);
		namesMap.put("AMBIKA SONI",164336);
		namesMap.put("AMEETA SINH",274028);
		namesMap.put("AMITBHAI ANILCHANDRA SHAH (AMIT SHAH)",188833);
		namesMap.put("AMITKUMAR AJITKUMAR CHAVDA",188184);
		namesMap.put("AMRUTIYA KANTILAL SHIVLAL",187351);
		namesMap.put("ANAM RAMANARAYANA REDDY",2767);
		namesMap.put("ANAM VIVEKANANDA REDDY",2801);
		namesMap.put("ANANDAN M",16104);
		namesMap.put("ANANTHA VENKATA RAMI REDDY",30559);
		namesMap.put("ANASUYA  DANSARI",1274);
		namesMap.put("ANIL JOSHIYARA",188019);
		namesMap.put("ANIL KUMAR  ERAVATHRI",173);
		namesMap.put("ANIPI REDDY  VENKATA PRAVEEN KUMAR REDDY",3480);
		namesMap.put("ANJAN KUMAR YADAV M",30197);
		namesMap.put("ANNA  RAMBABU",2725);
		namesMap.put("ANNAPURNA  ALETI",99);
		namesMap.put("ANNAYYAGARI SAI PRATHAP",30620);
		namesMap.put("ANTO ANTONY",33152);
		namesMap.put("ANUMULA  REVANTH REDDY",816);
		namesMap.put("ANUP KUMAR SAHA",37250);
		namesMap.put("ANUPRIYA PATEL",274264);
		namesMap.put("APPALA NARASAIAH  BOTSA",1521);
		namesMap.put("APPALANAIDU  BADDUKONDA",1529);
		namesMap.put("ARAVINDA REDDY GADDAM",25);
		namesMap.put("AREPALLY MOHAN",279);
		namesMap.put("ARJUNBHAI DEVABHAI MODHAVADIYA",188660);
		namesMap.put("ARUNA D K",900);
		namesMap.put("ARUNA KUMAR VUNDAVALLI",30429);
		namesMap.put("ARUNA KUMARI GALLA",3335);
		namesMap.put("ARUNA PADALA",1522);
		namesMap.put("ASADUDDIN OWAISI",6753);
		namesMap.put("ASHOK BHATT",161526);
		namesMap.put("ASHOK GAJAPATHIRAJU PUSANATI",1540);
		namesMap.put("ASHWANI KUMAR SHARMA",226610);
		namesMap.put("ASHWIN KOTVAL",188011);
		namesMap.put("ASNOTIKAR ANAND VASANT",170811);
		namesMap.put("ATHRAM SAKKU",38);
		namesMap.put("AUDIMULAPU  SURESH",2575);
		namesMap.put("AYYANNA PATRUDU CHINTAKAYALA",1704);
		namesMap.put("B  K  PARTHA SARATHI",3233);
		namesMap.put("B GURUNATHA REDDY",3434);
		namesMap.put("B N BACHHE GOWDA",170594);
		namesMap.put("B N VIJAYA KUMAR",2642);
		namesMap.put("B SREERAMULU",169909);
		namesMap.put("B SREERAMULU  ",11229);
		namesMap.put("BAALU T R",35760);
		namesMap.put("BADRUDDIN AJMAL",30680);
		namesMap.put("BALINENI SRINIVASA REDDY (VASU)",2656);
		namesMap.put("BALKRISHNA KHANDERAO SHUKLA",32035);
		namesMap.put("BALU NAIK  NENAVATH",3634);
		namesMap.put("BANDARI  RAJI REDDY",457);
		namesMap.put("BANDARU  SATYANANDA RAO",1879);
		namesMap.put("BANDARU DATTATREYA",30198);
		namesMap.put("BANDARU SATYANANDA RAO",5605);
		namesMap.put("BANSA GOPAL CHOWDHURY",37202);
		namesMap.put("BAPIRAJU KANUMURU",30440);
		namesMap.put("BARAD BHAGAVANBHAI DHANABHAI",187540);
		namesMap.put("BAROT BHARATKUMAR CHIMANLAL (BHARAT BAROT)",187768);
		namesMap.put("BASWARAJU SARAIAH",1227);
		namesMap.put("BATTI  VIKRAMARKA MALLU",1333);
		namesMap.put("BEEDA  MASTHAN RAO",2757);
		namesMap.put("BENI PRASAD VERMA",36458);
		namesMap.put("BHALALA KANUBHAI MEPABHAI",187560);
		namesMap.put("BHANUBEN MANOHARBHAI BABARIYA",187400);
		namesMap.put("BHIL DHIRUBHAI CHUNILAL",188208);
		namesMap.put("BHUMA  SHOBHA NAGI REDDY",2965);
		namesMap.put("BHUVA MANSUKHBHAI PANCHABHAI",187602);
		namesMap.put("BHUWAN CHANDRA KHANDURI",47711);
		namesMap.put("BIJOY KRISHNA HANDIQUE",30711);
		namesMap.put("BIJOYA CHAKRAVARTY",30699);
		namesMap.put("BIKRAM SINGH MAJITHIA",225054);
		namesMap.put("BIKSHAPATHI YADAV  M",547);
		namesMap.put("BIKSHAPATHY MOLUGURI",1203);
		namesMap.put("BIREN SINGH ENGTI",30660);
		namesMap.put("BODDEPALLI  SATYAVATHI",1433);
		namesMap.put("BOLEM  MUTHYALA PAPA",1703);
		namesMap.put("BOLEM MUTYALA PAPA",212574);
		namesMap.put("BOTCHA SATYANARAYANA",41936);
		namesMap.put("BUCHEPALLI  SIVA PRASADA REDDY",2590);
		namesMap.put("BUDIDA  BIKSHAMAIAH",1119);
		namesMap.put("BURUGUPALLI  SESHA RAO",1958);
		namesMap.put("C  R  PATIL",31919);
		namesMap.put("C D MEYYAPPAN",276456);
		namesMap.put("C DAMODAR RAJANARSIMHA",342);
		namesMap.put("C K JAYACHANDRA REDDY @ C K BABU",227181);
		namesMap.put("C K RAULJI",188105);
		namesMap.put("C RAMACHANDRAIAH",12164);
		namesMap.put("C T RAVI",170202);
		namesMap.put("CHADA VENKAT REDDY",308);
		namesMap.put("CHALAMALASETTY SUNIL",30403);
		namesMap.put("CHANDANA  RAMESH",1926);
		namesMap.put("CHANDAR RAO VANEPALLI",7128);
		namesMap.put("CHANDRA MOHANA REDDY SOMIREDDY",6143);
		namesMap.put("CHANDRAVATHI  BANOTH",1342);
		namesMap.put("CHANDRESH KUMARI",35250);
		namesMap.put("CHARANDAS MAHANT",31556);
		namesMap.put("CHAUDHARI CHHANABHAI KOLUBHAI",188455);
		namesMap.put("CHAUDHARI SHANKARBHAI LAGDHIRBHAI",187955);
		namesMap.put("CHAUDHARI TUSHARBHAI AMRASINHBHAI",31770);
		namesMap.put("CHAUDHARY JITUBHAI HIRJIBHAI",188459);
		namesMap.put("CHAUHAN DEVUSINH JESINGBHAI",31899);
		namesMap.put("CHAUHAN FATESINH VAKHATSINH",188089);
		namesMap.put("CHAUHAN JAYSINHJI MANSINHJI",188037);
		namesMap.put("CHAUHAN KHUMANSINH RAYSINH",188233);
		namesMap.put("CHAUHAN MANSHINH KOHYABHAI",190044);
		namesMap.put("CHAUHAN SUNDARSINH BHALABHAI",188146);
		namesMap.put("CHAVDA JAWAHAR PETHALJIBHAI",276461);
		namesMap.put("CHENGALA VENKATARAO",1694);
		namesMap.put("CHENNAMANENI VIDYASAGAR RAO",257);
		namesMap.put("CHIDAMBARAM P",22155);
		namesMap.put("CHINNAM  RAMAKOTAIAH",2130);
		namesMap.put("CHINTA MOHAN",30610);
		namesMap.put("CHINTHAKUNTA VIJAYA RAMANA RAO",229);
		namesMap.put("CHINTHALAPUDI  VENKATARAMAIAH",1615);
		namesMap.put("CHIRUMARTHY LINGAIAH",1092);
		namesMap.put("CHITTHAN N S V",26435);
		namesMap.put("CHITTHAN N S V",40209);
		namesMap.put("CHOUDHURY MOHAN JATUA",37467);
		namesMap.put("CHURCHILL ALEMAO",265723);
		namesMap.put("COL SONARAM CHOUDHARY",43929);
		namesMap.put("D  Y  DAS",2212);
		namesMap.put("D V SADANANDA GOWDA",32993);
		namesMap.put("DABHI BHARATSINHJI SHANKARJI",187918);
		namesMap.put("DABHI CHANDUBHAI MOTIBHAI",188279);
		namesMap.put("DADI VEERABHADRA RAO",1664);
		namesMap.put("DAGGUBATI PURANDARESWARI",30380);
		namesMap.put("DAGGUBATI VENKATESHWARA RAO",2605);
		namesMap.put("DANAM  NAGENDER",665);
		namesMap.put("DASARI VENKATA BALAVARDHANA RAO",2145);
		namesMap.put("DASYAM  VINAYA BHASKER",1212);
		namesMap.put("DASYAM VINAYA BHASKER",7039);
		namesMap.put("DAVE VIBHAVARIBEN VIJAYBHAI (VIBHABEN DAVE)",187685);
		namesMap.put("DAYANIDHI MARAN",35391);
		namesMap.put("DEEPA DASMUNSI",37509);
		namesMap.put("DESAI BABUBHAI JESANGBHAI",187978);
		namesMap.put("DESAI DOLATRAI NATHUBHAI",188450);
		namesMap.put("DESAI PANKAJKUMAR VINUBHAI (GOTIYO)",188156);
		namesMap.put("DESHMUKH SUBHASH SURESHCHANDRA",39577);
		namesMap.put("DEVJIBHAI GOVINDBHAI FATEPARA",38364);
		namesMap.put("DHARMANA  KRISHNA DAS",1449);
		namesMap.put("DHARMANA PRASADA RAO",1424);
		namesMap.put("DHORAJIYA HANUBHAI (BHABHA)",187588);
		namesMap.put("DHULIPALLA NARENDRA KUMAR",2366);
		namesMap.put("DIGAMBAR KAMAT",265712);
		namesMap.put("DILEEP SANGHANI",38395);
		namesMap.put("DINESH TRIVEDI",37265);
		namesMap.put("DINESHBHAI B PATEL (DINUMAMA)",188273);
		namesMap.put("DINSHA PATEL",31898);
		namesMap.put("DIP GOGOI",30719);
		namesMap.put("DIRISAM  PADMA JYOTHI",2114);
		namesMap.put("DIVAKAR REDDY J C",3159);
		namesMap.put("DOKKA  MANIKYA VARA PRASADA RAO",2341);
		namesMap.put("DOSHI VARSHABEN NARENDRABHAI",187315);
		namesMap.put("DR  J GEETA",358);
		namesMap.put("DR  JAYA PRAKASH NARAYAN",441);
		namesMap.put("DR  MANDA JAGANNATH",30283);
		namesMap.put("DR  RATNA DE",37345);
		namesMap.put("DR  TARUN MONDAL",37394);
		namesMap.put("DR  THATIKONDA RAJAIAH",5197);
		namesMap.put("DR D L RAVINDRA REDDY",2951);
		namesMap.put("DR K LAXMAN",6638);
		namesMap.put("DR NAGAM JANARDHAN REDDY",934);
		namesMap.put("DR P RAVI",3624);
		namesMap.put("DR P SHANKAR RAO",4782);
		namesMap.put("DR RAM CHANDRA DOME",37296);
		namesMap.put("DR RAVATHIPATHI KORLA",3740);
		namesMap.put("DR SAKE SAILAJANATH",3174);
		namesMap.put("DR SOLANKI KIRITBHAI PREMJIBHAI",31708);
		namesMap.put("DR VENUGOPAL P",35837);
		namesMap.put("DR. LAXMIKANT BAJPAI",275524);
		namesMap.put("DR. MOH. AYUB",273851);
		namesMap.put("DR. NIMAICHAND LUWANG",265886);
		namesMap.put("DRONAMRAJU  SRINIVASA RAO",1576);
		namesMap.put("DUDDILLA SRIDHAR BABU",219);
		namesMap.put("DURGA PRASAD RAO BALLI",2824);
		namesMap.put("DUSHYANTBHAI RAJNIKANT PATEL",188301);
		namesMap.put("DWARMAPUDI  CHANDRA SEKHARA REDDY",1809);
		namesMap.put("E  AHAMED",33132);
		namesMap.put("E AHAMED",43027);
		namesMap.put("E T  MUHAMMED BASHEER",33164);
		namesMap.put("EANUGU  RAVINDER REDDY",131);
		namesMap.put("EATALA RAJENDER",291);
		namesMap.put("ELANGOVAN T K S",35416);
		namesMap.put("ELI  VENKATA MADHUSUDHANARAO (NANI)",2043);
		namesMap.put("Eli Venkata Madhusudhana Rao",79441);
		namesMap.put("ENDALA  LAKSHMI NARAYANA",151);
		namesMap.put("ERASU PRATAP REDDY",6539);
		namesMap.put("ERRABELLI DAYAKAR RAO",1160);
		namesMap.put("ESHWAR KOPPULA",198);
		namesMap.put("FALDU RANCHHODBHAI CHANABHAI (R C FALDU)",187458);
		namesMap.put("FAROOQ ABDULLAH",32323);
		namesMap.put("G  PRASAD KUMAR",587);
		namesMap.put("G JAIPAL YADAV",956);
		namesMap.put("G KISHAN REDDY",649);
		namesMap.put("G Prasad Kumar",203933);
		namesMap.put("G VIVEKANAND",30127);
		namesMap.put("GADA BABULAL MEGHAJI SHAH",189353);
		namesMap.put("GADE VENKATA REDDY",2427);
		namesMap.put("GADIKOTA  SRIKANTH REDDY",3493);
		namesMap.put("GAGANJIT SINGH",225382);
		namesMap.put("GAIKHANGAM",262779);
		namesMap.put("GALI MUDDUKRISHNAMA NAIDU",3470);
		namesMap.put("GAMIT PUNABHAI DHEDABHAI",188364);
		namesMap.put("GAMPA  GOVERDHAN",143);
		namesMap.put("GANDHISELVAN S",16160);
		namesMap.put("GANDLURU  VEERA SIVA REDDY",2908);
		namesMap.put("GANESHAMURTHI A",16338);
		namesMap.put("GANGULA KAMALAKAR",3528);
		namesMap.put("GANGULA PRATHAPA REDDY",2966);
		namesMap.put("GANTA  SRINIVASA RAO",1662);
		namesMap.put("GAVIREDDY  RAMANAIDU",1635);
		namesMap.put("GILITWALA RANJITBHAI MANGUBHAI",188399);
		namesMap.put("GOBINDA CHANDRA NASKAR",37224);
		namesMap.put("GODAM NAGESH",71);
		namesMap.put("GOHIL SHAKTISINHJI HARISHCHANDRASINHJI",188811);
		namesMap.put("GOHIL UPENDRASINH PRATAPSINH",42726);
		namesMap.put("GOLLA  BABURAO",1693);
		namesMap.put("GONUGUNTLA  VENKATA SEETA RAMA ANJANEYULU",2525);
		namesMap.put("GOPALA KRISHNA REDDY BOJJALA",6165);
		namesMap.put("GORANTALA BUCHAIAH CHOWDARY",1917);
		namesMap.put("GOTTIPATI  RAVI KUMAR",2615);
		namesMap.put("GOVIND M KARJOL",171153);
		namesMap.put("GOVINDBHAI UKABHAI PATEL",187385);
		namesMap.put("GULAB  SINGH",276459);
		namesMap.put("GULAM NABI AZAD",166316);
		namesMap.put("GULSINGHBHAI RANGALABHAI RATHVA",188201);
		namesMap.put("GULZAR SINGH RANIKE",225099);
		namesMap.put("GUMMADI KUTHUHALAMMA",3390);
		namesMap.put("GUNDA MALLESH",18);
		namesMap.put("GURDAS SINGH BADAL",266248);
		namesMap.put("GURRALA VENKATA SESHU",6033);
		namesMap.put("GURUDAS DASGUPTA",37338);
		namesMap.put("GUTHA SUKENDER REDDY",30295);
		namesMap.put("H  HEMALATHA",3381);
		namesMap.put("HALPATI KUVARJIBHAI NARSINHBHAI",188373);
		namesMap.put("HANMANTH  SHINDE",116);
		namesMap.put("HARAK SINGH RAWAT",246221);
		namesMap.put("HARBANS KAPOOR",223906);
		namesMap.put("HARISH RAWAT",37138);
		namesMap.put("HARSHADBHAI CHUNILAL VASAVA",188335);
		namesMap.put("HELEN DAVIDSON J",35571);
		namesMap.put("HIRA SINGH GABRIA",225281);
		namesMap.put("INDIRA GANDHI",164795);
		namesMap.put("INDIRA HRIDAYESH",224205);
		namesMap.put("IQBAL PATEL",188293);
		namesMap.put("ISHVERBHAI NARSINHBHAI VAHIA",192402);
		namesMap.put("ISHWAR DASS DHIMAN",239045);
		namesMap.put("ISMAIL HUSSAIN",30666);
		namesMap.put("J K  RITHEESH  K",35714);
		namesMap.put("JADEJA BRIJRAJSINH HEMATSINH",187469);
		namesMap.put("JAGADISH SHETTAR",170603);
		namesMap.put("JAGATHRAKSHAKAN S",25472);
		namesMap.put("JAI RAM THAKUR",239143);
		namesMap.put("JAIPAL REDDY SUDINI",30237);
		namesMap.put("JANA REDDY KUNDURU",978);
		namesMap.put("JANARDHANA THOTRAJ  VEERAVARA THODARAMALA",1474);
		namesMap.put("JANMEJA SINGH",166661);
		namesMap.put("JASVANTSINH SUMANBHAI BHABHOR",188118);
		namesMap.put("JASWANT SINGH",35033);
		namesMap.put("JAYA PRAKASH REDDY  T",372);
		namesMap.put("JAYALALITHA J",20233);
		namesMap.put("JAYAMANGALA  VENKATA RAMANA",2170);
		namesMap.put("JAYAMANI  SAVARAPU",1481);
		namesMap.put("Jayamani Savarapu",135066);
		namesMap.put("JAYANT CHAUDHARY",36760);
		namesMap.put("JAYANTBHAI RAMANBHAI PATEL",38464);
		namesMap.put("JAYANTILAL PARSOTTAM BHANUSHALI",187263);
		namesMap.put("JAYASUDHA  KAPOOR",789);
		namesMap.put("JEYADURAI S R",35814);
		namesMap.put("JHANSI LAKSHMI BOTCHA",30372);
		namesMap.put("JITENDRA SINGH",35046);
		namesMap.put("JITENDRA SUKHADIYA",188244);
		namesMap.put("JOGESWARA RAO V",1890);
		namesMap.put("JOGI  RAMESH",2180);
		namesMap.put("JOGU RAMANNA",57);
		namesMap.put("JOSE K MANI",33097);
		namesMap.put("JOSEPH TOPPO",30799);
		namesMap.put("JOSHI C P",35087);
		namesMap.put("JOTVA RAJSIBHAI VIRABHAI",187545);
		namesMap.put("JULAKANTI RANGA REDDY",998);
		namesMap.put("JUPALLY KRISHNA RAO",964);
		namesMap.put("JUTTU  JAGANNAIKULU",1402);
		namesMap.put("JYOTIRADITYA MADHAVRAO SCINDIA",33367);
		namesMap.put("K  MEENAKSHI NAIDU",3129);
		namesMap.put("K  SUDHAKAR",3214);
		namesMap.put("K  SUDHAKARAN",33071);
		namesMap.put("K C VENUGOPAL",33012);
		namesMap.put("K CHANDRASEKHAR RAO",30251);
		namesMap.put("K CHENNAKESAVA REDDY",4658);
		namesMap.put("K E KRISHNA MURTHY",3070);
		namesMap.put("K H MUNIYAPPA",32903);
		namesMap.put("K P DHANAPALAN",33041);
		namesMap.put("K S RATNAM",37740);
		namesMap.put("K V P RAMACHANDRA RAO",241076);
		namesMap.put("K VIJAYA RAMA RAO",666);
		namesMap.put("KABINDRA PURKAYASTHA",30785);
		namesMap.put("KABIR SUMAN",37369);
		namesMap.put("KADIYAM  SREEHARI",1150);
		namesMap.put("KAGERI VISHWESHWAR HEGDE",171604);
		namesMap.put("KAKADIYA VALLABHBHAI GOBARBHAI (VALLABHBHAI HIRAWALA)",187809);
		namesMap.put("Kakala Venkata Rao",70553);
		namesMap.put("KAKALI GHOSH DASTIDAR",37242);
		namesMap.put("KALIDINDI  SURYA NAGA SANYASI RAJU",1626);
		namesMap.put("KALRAJ MISHRA",274604);
		namesMap.put("KALSHARIYA KANUBHAI VALABHAI",187664);
		namesMap.put("KALUBHAI VIRANI",187654);
		namesMap.put("KALVAKUNTA CHANDRASHEKHAR RAO",4975);
		namesMap.put("KALVAKUNTALA TARAKA RAMARAO",263);
		namesMap.put("KALVAKUNTLA VIDYASAGAR RAO",180);
		namesMap.put("KALYAN BANERJEE",37527);
		namesMap.put("KAMAL AKHTAR",251254);
		namesMap.put("KAMAL NATH",33298);
		namesMap.put("KAMALA  KANDRU",2350);
		namesMap.put("KAMALAMMA  P M",2850);
		namesMap.put("KAMAT DIGAMBAR",261231);
		namesMap.put("KAMBALAPADU  EDIGA PRABHAKAR",3085);
		namesMap.put("KAMBHAM VIJAYARAMI REDDY",6084);
		namesMap.put("KANDIKUNTA  VENKATA PRASAD",3281);
		namesMap.put("KANDULA  NARAYANA REDDY",2709);
		namesMap.put("KANNA LAKSHMI NARAYANA",4178);
		namesMap.put("KANZARIYA MEGHJI DAYA",187485);
		namesMap.put("KAPIL SIBAL",34503);
		namesMap.put("KAPU  RAMACHANDRA REDDY",3462);
		namesMap.put("KARANAM  DHARMASRI",1627);
		namesMap.put("KARANAM BALARAMA KRISHNA MURTHY",2616);
		namesMap.put("KARGATIA BHAGVANJI LAKHABHAI",276467);
		namesMap.put("KARUMURI  VENKATA NAGESWARA RAO",2033);
		namesMap.put("KARUNAKAR REDDY  BHUMANA",3348);
		namesMap.put("KASU VENKATA KRISHNA REDDY",4212);
		namesMap.put("KATAMREDDY VISHNUVARDHAN REDDY",2758);
		namesMap.put("KATARI  SRINIVASA RAO",550);
		namesMap.put("Katari Srinivasa Rao",84933);
		namesMap.put("KATASANI  RAMI REDDY",3053);
		namesMap.put("KATASANI RAMA BHUPAL REDDY",3022);
		namesMap.put("KAVALI PRATHIBHA BHARATHI",5404);
		namesMap.put("KAVETI SAMMAIAH",1);
		namesMap.put("KAVITHA  MALOTH",1181);
		namesMap.put("KAVURU  SAMBA SIVA RAO",30450);
		namesMap.put("KESHARI NATH TRIPATHI",40822);
		namesMap.put("KETHIREDDY  VENKATA RAMI REDDY",3258);
		namesMap.put("KHEDAWALA SABIRBHAI ABDULKARIM (SABIRBHAI KABLIWALA)",187837);
		namesMap.put("KHIMI RAM",239137);
		namesMap.put("KICHANNAGARI  LAXMA REDDY (KLR)",414);
		namesMap.put("KILLI KRUPARANI",30366);
		namesMap.put("KIRANKUMAR LAKSHMANBHAI MAKWANA",188283);
		namesMap.put("KISHAN CHAND KAPOOR",239282);
		namesMap.put("KISHANBHAI VESTABHAI PATEL",32042);
		namesMap.put("KISHOR VANKAWALA",188410);
		namesMap.put("KISHORE CHANDRA SURYANARAYANA DEO VYRICHERLA",30356);
		namesMap.put("KISHORI BACHUBHAI NATHABHAI",188066);
		namesMap.put("KODALI  SRI VENKATESWARA RAO (NANI)",2157);
		namesMap.put("KODELA SIVA PRASADA RAO",2502);
		namesMap.put("KODIKKUNNIL SURESH",33136);
		namesMap.put("KODNANI MAYABEN SURENDRABHAI",188915);
		namesMap.put("KOLLA  LALITHA KUMARI",1550);
		namesMap.put("KOMATI REDDY RAJ GOPAL REDDY",30307);
		namesMap.put("KOMATIREDDY VENKAT REDDY",1055);
		namesMap.put("KOMMALAPATI  SRIDHAR",2328);
		namesMap.put("KONAKALLA NARAYANA RAO",30460);
		namesMap.put("KONATHALA RAMAKRISHNA",1663);
		namesMap.put("KONDA SUREKHA",1202);
		namesMap.put("KONDETI  SRIDHAR",1242);
		namesMap.put("KONDRU MURALI MOHAN",5405);
		namesMap.put("KONIDALA  CHIRANJEEVI",1984);
		namesMap.put("KOPPULA HARISHWAR REDDY",575);
		namesMap.put("KORAMUTLA  SRINIVASULU",2887);
		namesMap.put("KORAT JASHUBEN SAVAJIBHAI",188590);
		namesMap.put("KOSURI  KASI VISWANADHA VEERA VENKATA SATYANARAYANA REDD",1711);
		namesMap.put("KOTHAPALLI SUBBARAYUDU (PEDA BABU)",3952);
		namesMap.put("KOTLA JAYASURYA PRAKASHA REDDY",30549);
		namesMap.put("KOTLA SUJATHAMMA",3071);
		namesMap.put("KRISHNA TIRATH",34611);
		namesMap.put("KRISHNASAMY M",35383);
		namesMap.put("KRISTAPPA NIMMALA",30571);
		namesMap.put("KU  RATANJEET PRATAP NARAYAN SINGH",36657);
		namesMap.put("KUMAR P",18592);
		namesMap.put("KUMAR P   ",37568);
		namesMap.put("KUNA  PANDU VIVEKANAND",427);
		namesMap.put("KUNA SRISAILAM GOUD",426);
		namesMap.put("KUNAMNENI  SAMBASIVA RAO",1363);
		namesMap.put("KUNDARIYA MOHANBHAI KALYANJI",188547);
		namesMap.put("KUNJA  SATYAVATHI",1388);
		namesMap.put("KUNVARJIBHAI MOHANBHAI BAVALIYA",188558);
		namesMap.put("KUNWAR JITIN PRASAD",36265);
		namesMap.put("KUNWAR REWATI RAMAN SINGH",35972);
		namesMap.put("KURASALA  KANNABABU",1762);
		namesMap.put("KURUGONDLA  RAMA KRISHNA",2841);
		namesMap.put("L RAMANA",6955);
		namesMap.put("LABBI  VENKATA SWAMY",2988);
		namesMap.put("LAGADAPATI RAJAGOPAL",30470);
		namesMap.put("LAKHAWALA BHUPENDRABHAI GATULAL",188238);
		namesMap.put("LAKSHMI KANTA CHAWLA",225076);
		namesMap.put("LAKUM KANTIBHAI RAMABHAI",188825);
		namesMap.put("LAL CHAND KATARIA",35184);
		namesMap.put("LAL KRISHNA ADVANI",31824);
		namesMap.put("LALIT MOHAN SUKLABAIDYA",37826);
		namesMap.put("LALIT MOHAN SUKLABAIDYA   ",30727);
		namesMap.put("LALJIBHAI PREMJIBHAI SOLANKI",187446);
		namesMap.put("LINGAA REDDY  MALLELA",2938);
		namesMap.put("LINGAM P",35784);
		namesMap.put("LOUISE KHURSHID",41041);
		namesMap.put("M  SHAJAHAN BASHA (JAHA)",3308);
		namesMap.put("M B  RAJESH",33142);
		namesMap.put("M I  SHANAVAS",33212);
		namesMap.put("M K  RAGHAVAN",33116);
		namesMap.put("M MUKESH GOUD",722);
		namesMap.put("M SRINIVAS",42940);
		namesMap.put("M VEERAPPA MOILY",32777);
		namesMap.put("MACHHAR DITABHAI BHIMABHAI",188063);
		namesMap.put("MADDALA  RAJESH KUMAR",2102);
		namesMap.put("MADHU YASHKI GOUD",30153);
		namesMap.put("MADHUSUDAN",3152);
		namesMap.put("MAHADEV SINGH",35322);
		namesMap.put("MAHARAUL TUSHARSINH KANAKSINH",188083);
		namesMap.put("MAHEEDHAR REDDY MANUGUNTA",2681);
		namesMap.put("MAHENDER SINGH",32071);
		namesMap.put("MAHENDRA KUMAR ROY",37379);
		namesMap.put("MAHESH INDER SINGH",225500);
		namesMap.put("MAHESHWARI RAMESH VACHCHHRAJ",187286);
		namesMap.put("MAJ GEN(RETD.) BHUWAN CHANDRA KHANDURI AVSM",265403);
		namesMap.put("MAKADIYA PRAVINBHAI MOHANBHAI",187428);
		namesMap.put("MAKVANA BHAVNABEN RAGHAVJIBHAI",187674);
		namesMap.put("MAKWANA VANDNABEN MANSHUKHBHAI",187537);
		namesMap.put("MALI ANILKUMAR AMRUTLAL",187971);
		namesMap.put("MALIK SAKTI MOHAN",37197);
		namesMap.put("MALLADI  VISHNU",2255);
		namesMap.put("MALLIKARJUN KHARGE",32868);
		namesMap.put("MALLIPUDI MANGAPATI PALLAM RAJU",30402);
		namesMap.put("MAMATA BANERJEE",37414);
		namesMap.put("MANCHIREDDY  KISHAN REDDY",477);
		namesMap.put("MANDALI BUDHA PRASAD",2202);
		namesMap.put("MANDAVA VENKATESHWARA RAO",5044);
		namesMap.put("MANEK PABUBHA VIRAMBHA",187490);
		namesMap.put("MANEKA GANDHI",40463);
		namesMap.put("MANIAN O S",35648);
		namesMap.put("MANICKA TAGORE",35892);
		namesMap.put("MANISH TEWARI",34983);
		namesMap.put("MANMOHAN SINGH",32076);
		namesMap.put("MANMOHAN SINGH ",276229);
		namesMap.put("MANOHAR TIRKEY",37188);
		namesMap.put("MANORANJAN KALIA",225139);
		namesMap.put("MANPREET SINGH BADAL",225489);
		namesMap.put("MARRI SHASHIDHAR REDDY",694);
		namesMap.put("MASHROO MAHENDRA LILADHAR",188735);
		namesMap.put("MATA PRASAD PANDEY",36277);
		namesMap.put("MATBAR SINGH KANDARI",224109);
		namesMap.put("MAUSAM NOOR",37458);
		namesMap.put("MAYAWATI",44476);
		namesMap.put("MEESALA  NEELAKANTAM",1441);
		namesMap.put("MEESALA NEELAKANTAM",5408);
		namesMap.put("MEKAPATI  CHANDRA SEKHAR REDDY",3582);
		namesMap.put("MEKAPATI RAJAMOHAN REDDY",13626);
		namesMap.put("MER RANCHHODBHAI KARSHANBHAI",187705);
		namesMap.put("MILIND MURLI DEORA",34083);
		namesMap.put("MITHRASENA  VAGGELA",1378);
		namesMap.put("MITRASEN YADAV",47887);
		namesMap.put("MODUGULA VENU GOPALA REDDY",30498);
		namesMap.put("MOHAMMAD AZAM KHAN",252783);
		namesMap.put("MOHAN LAL",10894);
		namesMap.put("MOHANSINH CHHOTUBHAI RATHAVA",188205);
		namesMap.put("MOHD  MOAZAM KHAN",778);
		namesMap.put("MOHD  MUQTADA KHAN",709);
		namesMap.put("MOHD  VIRASAT RASOOL KHAN",3507);
		namesMap.put("MOPIDEVI VENKATA RAMANA RAO",2392);
		namesMap.put("MOTHUKUPALLI NARSIMHULU",1106);
		namesMap.put("MUDUNURI  PRASADA RAJU",1996);
		namesMap.put("MUKHTAR ANSARI",37104);
		namesMap.put("MUKUL ROY",59154);
		namesMap.put("MUKUL WASNIK",34288);
		namesMap.put("MULAYAM SINGH YADAV",36746);
		namesMap.put("MULLAPPALLY RAMACHANDRAN",33204);
		namesMap.put("MUMTAZ AHMED KHAN",766);
		namesMap.put("MUNGAMURU  SRIDHAR KRISHNA REDDY",2789);
		namesMap.put("MUTTAMSETTI  SRINIVASA RAO (AVANTHI SIRNU)",3614);
		namesMap.put("MYNAMPALLI  HANUMANTH RAO",3555);
		namesMap.put("N CHELUVARAYA SWAMY",32942);
		namesMap.put("NADENDLA  MANOHAR",2409);
		namesMap.put("NAKARANI KESHUBHAI HIRAJIBHAI",187649);
		namesMap.put("NALLALA ODELU",9);
		namesMap.put("NALLAMILLI  SHESHAREDDY",1789);
		namesMap.put("NALLAPAREDDY  PRASANNA KUMAR REDDY",2778);
		namesMap.put("NALLARI KIRAN KUMAR REDDY",3297);
		namesMap.put("NAMA NAGESWARA RAO",30345);
		namesMap.put("NAMO NARAIN MEENA",35337);
		namesMap.put("NANDAMURI LAKSHMI PARVATHI",5353);
		namesMap.put("NANDAMURI TARAKA RAMA RAO",7203);
		namesMap.put("NANDYALA VARADARAJULA REDDY",2939);
		namesMap.put("NAPOLEON D",17309);
		namesMap.put("NARA CHANDRABABU NAIDU",3424);
		namesMap.put("NARAHARI MAHATO",37495);
		namesMap.put("NARAMALLI SIVAPRASAD",30634);
		namesMap.put("NARAYANASAMY",21406);
		namesMap.put("NARENDRA MODI",187847);
		namesMap.put("NAROTTAMBHAI PATEL",188417);
		namesMap.put("NATARAJAN P R",35477);
		namesMap.put("NATVARSINH FULSINH THAKOR",188149);
		namesMap.put("NAVEEN JINDAL",32183);
		namesMap.put("NAVJOT SIDHU",266030);
		namesMap.put("NAWAB KAZIM ALI KHAN ALIAS NAVED MIAN",241213);
		namesMap.put("NAYINI NARSIMHA REDDY",617);
		namesMap.put("NEDURUMALLI RAJYALAKSHMI",2842);
		namesMap.put("NEELAKANTAPURAM  RAGHUVEERA REDDY",3186);
		namesMap.put("NIMMAKA  SUGREEVULU",1466);
		namesMap.put("NINONG ERING",30653);
		namesMap.put("NIRANJAN P PATEL",189105);
		namesMap.put("NOMULA NARSIMHAIAH",5302);
		namesMap.put("NRIPENDRA NATH ROY",37303);
		namesMap.put("ODEDARA KARSANBHAI DULABHAI",187513);
		namesMap.put("OKRAM IBOBI SINGH",262948);
		namesMap.put("OKRAM JOY",264579);
		namesMap.put("OOMMEN CHANDY",49186);
		namesMap.put("P  ABDUL GHANI",3220);
		namesMap.put("P BABUMOHAN",6826);
		namesMap.put("P BALRAM",30334);
		namesMap.put("P C CHACKO",33193);
		namesMap.put("P JANARDHAN REDDY",4888);
		namesMap.put("P K BIJU",33018);
		namesMap.put("P KARUNAKARAN",33080);
		namesMap.put("P RAMULU",948);
		namesMap.put("P VIJAYA",552);
		namesMap.put("P VISHNUVARDHAN REDDY",681);
		namesMap.put("PABAN SINGH GHATOWAR",30689);
		namesMap.put("PABAN SINGH GHATOWAR",37903);
		namesMap.put("PALANIMANICKAM S S",35789);
		namesMap.put("PALLE  RAGHUNATHA REDDY",3244);
		namesMap.put("PAMULA  RAJESWARI DEVI",1871);
		namesMap.put("PANABAKA LAKSHMI",30511);
		namesMap.put("PANADA VAJESINGBHAI PARSINGBHAI",188069);
		namesMap.put("PANCHAKARLA  RAMESH BABU",1674);
		namesMap.put("PANTHAM  GANDHI MOHAN",1776);
		namesMap.put("PANTHAM GANDHI MOHAN",5524);
		namesMap.put("PARAS NATH YADAW",274052);
		namesMap.put("PARASA VENKATA RATNAIAH",6152);
		namesMap.put("PARESHBHAI GOVINDBHAI VASAVA",188344);
		namesMap.put("PARGAT SINGH",225945);
		namesMap.put("PARIGELA  MURALIKRISHNA",3098);
		namesMap.put("PARITALA  SUNEETHAMMA",3194);
		namesMap.put("PARKASH SINGH BADAL",225499);
		namesMap.put("PARMAR ATMARAM MAKANBHAI",187633);
		namesMap.put("PARMAR DILIPSINH VAKHATSINH",189028);
		namesMap.put("PARMAR JASHODABEN CHATURBHAI",187890);
		namesMap.put("PARMAR JAYADRATHSINHJEE CHANDRASINHJEE",189062);
		namesMap.put("PARMAR PARANJAYADITYASINHJI KRISHNAKUMARSINHJI",188057);
		namesMap.put("PARMAR RAJENDRASINH DHIRSINH",188190);
		namesMap.put("PARMAR RAMSINH PRABHATBHAI",189078);
		namesMap.put("PARMAR SHAILESH MANHARBHAI",187823);
		namesMap.put("PARMINDER SINGH DHINDSA",225423);
		namesMap.put("PARSHOTAMBHAI ODHAVJIBHAI SOLANKI",189651);
		namesMap.put("PARTHA SARATHY  KOLUSU",2225);
		namesMap.put("PARVATHA  SRI SATYANARAYANA MURTHY",1732);
		namesMap.put("PARVATHAMMA MAGUNTA",111975);
		namesMap.put("PASUPULETI  BALARAJU",1652);
		namesMap.put("PATEL ANANDIBEN MAFATBHAI",187936);
		namesMap.put("PATEL ANILKUMAR TRIBHOVANDAS",187895);
		namesMap.put("PATEL BABUBHAI JAMNADAS",188841);
		namesMap.put("PATEL GITABEN YOGESHBHAI",187755);
		namesMap.put("PATEL HARILAL MOHANLAL",187344);
		namesMap.put("PATEL HIRABHAI HARIBHAI",188112);
		namesMap.put("PATEL ISHWARSINH THAKORBHAI",188312);
		namesMap.put("PATEL JYOTSNABEN RAJUBHAI",188163);
		namesMap.put("PATEL KANTIBHAI RAMABHAI",188961);
		namesMap.put("PATEL KIRITBHAI GANGARAMBHAI",188382);
		namesMap.put("PATEL LAXMANBHAI PARSOTTAMBHAI",188438);
		namesMap.put("PATEL MANGUBHAI CHHAGANBHAI",188434);
		namesMap.put("PATEL MANIBHAI DEVJIBHAI",188125);
		namesMap.put("PATEL NARAYANBHAI LALLUDAS",187923);
		namesMap.put("PATEL NARESHBHAI MAGANBHAI",188441);
		namesMap.put("PATEL NITINKUMAR RATILAL",187882);
		namesMap.put("PATEL PARBATBHAI SAVABHAI",187964);
		namesMap.put("PATEL PRAFULLBHAI KHODABHAI",188030);
		namesMap.put("PATEL PRAGJIBHAI NARANBHAI",187721);
		namesMap.put("PATEL RAGHAVJIBHAI HANSRAJBHAI",187432);
		namesMap.put("PATEL RAJNIKANT SOMABHAI",187944);
		namesMap.put("PATEL RAMESHBHAI CHHOTUBHAI",192515);
		namesMap.put("PATEL RUSHIKESH GANESHBHAI",187914);
		namesMap.put("PATEL SURESHKUMAR CHATURDAS",187875);
		namesMap.put("PATEL USHABEN GIRISHKUMAR",188464);
		namesMap.put("PATEL VIJAYBHAI RAMESHBHAI",188445);
		namesMap.put("PATIL  NEERAJA REDDY",3450);
		namesMap.put("PATLOLLA KISTA REDDY",333);
		namesMap.put("PATLOLLA SABITHA",508);
		namesMap.put("PATNAM MAHENDER REDDY",599);
		namesMap.put("PAWAN KUMAR BANSAL",31472);
		namesMap.put("PAYYAVULA KESHAV",3140);
		namesMap.put("PEDDIREDDIGARI RAMACHANDRA REDDY",4447);
		namesMap.put("PEEDIKA  RAJANNA DORA",3766);
		namesMap.put("PEETHAMBARA KURUP N",33087);
		namesMap.put("PENDURTHI  VENKATESH",1906);
		namesMap.put("PERNI  VENKATRAMAIAH (NANI)",2190);
		namesMap.put("PINIPE  VISWARUPU",1852);
		namesMap.put("PIRIYA SAIRAJ",1397);
		namesMap.put("PIRJADA MAHMADJAVID ABDULMUTLIB",187369);
		namesMap.put("POCHARAM  SRINIVAS REDDY (PARIGE)",123);
		namesMap.put("PONNALA LAKSHMAIAH",1137);
		namesMap.put("PONNAM PRABHAKAR",30139);
		namesMap.put("POONAMBEN VELJIBHAI JAT",31881);
		namesMap.put("PRABHAKAR  CHINTAMANENI",2064);
		namesMap.put("PRABHAKARA RAO  TANGIRALA",2293);
		namesMap.put("PRABHU MANOHAR PARRIKAR",265619);
		namesMap.put("PRABODH PANDA",37474);
		namesMap.put("PRADEEP KUMAR JAIN ADITYA",36561);
		namesMap.put("PRADIPSINH BHAGVATSINH JADEJA",187797);
		namesMap.put("PRAFUL MANOHARBHAI PATEL",33760);
		namesMap.put("PRAJAPATI GOVINDBHAI MADHAVLAL",187994);
		namesMap.put("PRAKASH PANT",224310);
		namesMap.put("PRAKASH REDDY  REVURI",1191);
		namesMap.put("PRAMOD TIWARI",34609);
		namesMap.put("PRANAB MUKHERJEE",37389);
		namesMap.put("PRASANTA KUMAR MAJUMDAR",37216);
		namesMap.put("PRATAPSINGH RANE",265649);
		namesMap.put("PRATHIPATI  PULLA RAO",2486);
		namesMap.put("PRATHIPATI PULLA RAO",5981);
		namesMap.put("PRATIK PRAKASHRAO PATIL",34335);
		namesMap.put("PRENEET KAUR",35009);
		namesMap.put("PROF  K V THOMAS",33052);
		namesMap.put("PROF K V THOMAS",49069);
		namesMap.put("PROF PREM KUMAR DHUMAL",240120);
		namesMap.put("PROF VASUBEN TRIVEDI",187437);
		namesMap.put("PULIN BIHARI BASKE",37402);
		namesMap.put("PURANO AGITOK SANGMA",34492);
		namesMap.put("PUROHIT MAFATLAL MOTIRAM",187986);
		namesMap.put("R ASHOKA",171272);
		namesMap.put("R K ROJA",3336);
		namesMap.put("RADADIYA VITTHALBHAI HANSRAJBHAI",31954);
		namesMap.put("RADHABINOD KOIJAM",262569);
		namesMap.put("RAHUL GANDHI",36021);
		namesMap.put("RAJA A",35679);
		namesMap.put("RAJA BHAIYA",257390);
		namesMap.put("RAJA GOPAL SREERAM",2309);
		namesMap.put("RAJAIAH SIRICILLA",30320);
		namesMap.put("RAJANI LAVAJIBHAI THAKARSHIBHAI",187567);
		namesMap.put("RAJEN GOHAIN",30773);
		namesMap.put("RAJENDRA PRASAD ALAPATI",5858);
		namesMap.put("RAJENDRAN C",15902);
		namesMap.put("RAJENDRAN C",154276);
		namesMap.put("RAJESH TRIPATHI",40581);
		namesMap.put("RAJINDER KAUR",118354);
		namesMap.put("RAJIV GANDHI",127126);
		namesMap.put("RAJNATH SINGH",36422);
		namesMap.put("RAKESH SHAH",187762);
		namesMap.put("RAKESH VERMA",238979);
		namesMap.put("RAMA KRISHNA REDDY  PINNELLI",2553);
		namesMap.put("RAMA KRISHNA REDDY PINNELLI",4199);
		namesMap.put("RAMAKRISHNA BABU  VELAGAPUDI",1562);
		namesMap.put("RAMANJANEYULU  PULAPARLI (ANJIBABU)",2008);
		namesMap.put("RAMANLAL NANUBHAI PATKAR",188468);
		namesMap.put("RAMASUBBU S   ",37592);
		namesMap.put("RAMEN DEKA",30760);
		namesMap.put("RAMESH CHAND",39917);
		namesMap.put("RAMESH POKHRIYAL NISHANK",265257);
		namesMap.put("RAMIREDDY  PRATAP KUMAR REDDY",2759);
		namesMap.put("RAMREDDY DAMODAR REDDY",1036);
		namesMap.put("RAMREDDY VENKATA REDDY",5262);
		namesMap.put("RANA KIRITSINH JEETUBHA",187321);
		namesMap.put("RANE PRATAPSINGH RAOJIRAO",261174);
		namesMap.put("RANEE NARAH",30745);
		namesMap.put("RANINDER SINGH",34865);
		namesMap.put("RANJIT SINGH BRAHAMPURA",225113);
		namesMap.put("RAPAKA  VARA PRASADA RAO",1860);
		namesMap.put("RATHOD ARVINDSINH DAMSINH",188098);
		namesMap.put("RATHOD BHARTIBEN AMRUTBHAI",188377);
		namesMap.put("RATHOD BHAVSINHBHAI DAHYABHAI",187951);
		namesMap.put("RATHOD KALUBHAI CHANABHAI",187554);
		namesMap.put("RATHOD KAMABHAI GAGJIBHAI",187731);
		namesMap.put("RATHOD RAMESH",6887);
		namesMap.put("RAVI  YALAMANCHILI",2266);
		namesMap.put("RAVI NAIK",265664);
		namesMap.put("RAVINDER SINGH RAVI",239264);
		namesMap.put("RAVULA  CHANDDRA SHEKAR REDDY",888);
		namesMap.put("RAYAPATI  SAMBASIVA RAO",30488);
		namesMap.put("REGA  KANTHA RAO",1283);
		namesMap.put("RENUKA CHOWDHURY",30346);
		namesMap.put("RISHANG KEISHING",262979);
		namesMap.put("RITA BAHUGUNA JOSHI",36682);
		namesMap.put("ROHIT AMBALAL ASHABHAI",188180);
		namesMap.put("ROSAIAH KONIJETI",4229);
		namesMap.put("ROUTU SURYA PRAKASA RAO",1916);
		namesMap.put("S ALAGIRI",27614);
		namesMap.put("S M KRISHNA",32628);
		namesMap.put("S P Y REDDY",6529);
		namesMap.put("SABBAM HARI",5428);
		namesMap.put("SACHIN PILOT",35038);
		namesMap.put("SALMAN KHURSHEED",36340);
		namesMap.put("SANKAR ADHI",35534);
		namesMap.put("SANKINENI VENKATESHWAR RAO",227327);
		namesMap.put("SANSUMA KHUNGGUR BWISWMUTHIARY",30742);
		namesMap.put("SARVAIYA MAHENDRASINH PARAKRAMSINH",187640);
		namesMap.put("SARVEEN CHOUDHARY",239281);
		namesMap.put("SARVEY SATHYANARAYANA",30181);
		namesMap.put("SATABDI ROY",37282);
		namesMap.put("SATYANARAYANA  PITHANI",3974);
		namesMap.put("SATYAVATHI RATHOD",1172);
		namesMap.put("SAUGATA RAY",37332);
		namesMap.put("SAURABH PATEL",187621);
		namesMap.put("SELJA",32049);
		namesMap.put("SEMMALAI S",16054);
		namesMap.put("SENGHANI DHANJIBHAI",187269);
		namesMap.put("SHAIK  MASTAN VALI",2471);
		namesMap.put("SHAIK MASTAN VALI",10409);
		namesMap.put("SHAIKH GYASUDDIN HABIBUDDIN",187779);
		namesMap.put("SHAIKH MOHAMMAD FARUK HUSSAINMIYA(FARUK SHAIKH)",187790);
		namesMap.put("SHANKH LAL MANJHI",40628);
		namesMap.put("SHARADCHANDRA GOVINDRAO PAWAR",33971);
		namesMap.put("SHASHI THAROOR",33177);
		namesMap.put("SHIVPAL SINGH YADAV",247482);
		namesMap.put("SHRIVASTAV MADHUBHAI BABUBHAI",188261);
		namesMap.put("SHUKAL SHIRISHKUMAR MADHUSUDAN",188196);
		namesMap.put("SIDDHARTH CHIMANBHAI PATEL",188223);
		namesMap.put("SILPA  MOHAN REDDY",3038);
		namesMap.put("SIVASAMI C",16294);
		namesMap.put("SIVERI  SOMA",1644);
		namesMap.put("SK  NURUL ISLAM",37274);
		namesMap.put("SK  SAIDUL HAQUE",37257);
		namesMap.put("SMR BARIYA CHANDRIKABEN CHHAGANBHAI",188076);
		namesMap.put("SOLANKI BHARATBHAI MADHAVSINH",31740);
		namesMap.put("SOLANKI HIRABHAI ODHAVAJIBHAI",189599);
		namesMap.put("SOMARAPU SATHYANARAYANA",204);
		namesMap.put("SOMENDRA NATH MITRA",37322);
		namesMap.put("SONIA GANDHI",36933);
		namesMap.put("SREENIVASULU REDDY MAGUNTA",30521);
		namesMap.put("SRI PRAKASH JAISWAL",36623);
		namesMap.put("SRIKANTA KUMAR JENA",34663);
		namesMap.put("SUBHASH CHANDRA BOSE PILLI",1824);
		namesMap.put("SUBODH KANT SAHAY",32564);
		namesMap.put("SUCHA SINGH LANGAH",225032);
		namesMap.put("SUCHARITHA  MEKATHOTI",2440);
		namesMap.put("Sucharitha Mekathoti",66393);
		namesMap.put("SUCHARU RANJAN HALDAR",37521);
		namesMap.put("SUDDALA DEVAIAH",241);
		namesMap.put("SUDERSHAN REDDY",109);
		namesMap.put("SUDHEER REDDY  DEVIREDDY",488);
		namesMap.put("SUDIP BANDYOPADHYAY",37427);
		namesMap.put("SUGAVANAM  E G",35623);
		namesMap.put("SUGUMAR K",35700);
		namesMap.put("SUKHBIR SINGH BADAL",39840);
		namesMap.put("SUKHDEV RAJBHAR",273452);
		namesMap.put("SULTAN AHMED",14197);
		namesMap.put("SULTAN SALAHUDDIN OWAISI",14053);
		namesMap.put("SUMAN RATHOD",47);
		namesMap.put("SURAVARAM SUDHAKAR REDDY",10855);
		namesMap.put("SURESH KUMAR SHETKAR",30164);
		namesMap.put("SURYA PRATAP SHAHI",242257);
		namesMap.put("SUSHILKUMAR SAMBHAJIRAO SHINDE",34382);
		namesMap.put("SUSHMA SHARMA",239238);
		namesMap.put("SUSHMA SWARAJ",33644);
		namesMap.put("SUSMITA BAURI",37289);
		namesMap.put("SWAMI PRASAD MAURYA",36658);
		namesMap.put("SWARNA RAM",225192);
		namesMap.put("SYED  AHMED PASHA QUADRI",740);
		namesMap.put("T  MANEMMA",615);
		namesMap.put("T  PRAKASH GOUD",526);
		namesMap.put("T G VENKATESH",3007);
		namesMap.put("T NANDESHWAR GOUD",3568);
		namesMap.put("T PADMA RAO",695);
		namesMap.put("T SUBBARAMI REDDY",41939);
		namesMap.put("T V RAMA RAO",1946);
		namesMap.put("TADVI ABHESINH MOTIBHAI",188216);
		namesMap.put("TALASANI SRINIVAS YADAV",6665);
		namesMap.put("TALPADA KANJIBHAI RAYABHAI",187711);
		namesMap.put("TAMBIDURAI M",35588);
		namesMap.put("TAMMINENI SEETHARAM",5397);
		namesMap.put("TANETI  VANITA",2082);
		namesMap.put("TAPAS PAUL",37440);
		namesMap.put("TARIQ ANWAR",42383);
		namesMap.put("TEJ NARAYAN PANDEY ALIAS PAWAN PANDEY",273222);
		namesMap.put("TELLAM  BALA RAJU",2092);
		namesMap.put("THAKOR JODHAJI GALABJI",187930);
		namesMap.put("THAKOR SHAMBHUJI CHELAJI",187863);
		namesMap.put("THAMARAISELVAN  R",35501);
		namesMap.put("THANEERU  HARISH RAO",320);
		namesMap.put("THIRUMAAVALAVAN THOL",35468);
		namesMap.put("THOPUDURTHI  PRAKASH REDDY",3195);
		namesMap.put("THOTA  NARASIMHAM",1936);
		namesMap.put("THOTA  THRIMURTULU",1825);
		namesMap.put("THUMMALA  NAGESWARA RAO",1309);
		namesMap.put("TIKSHAN SUD",225211);
		namesMap.put("TULLA DEVENDER GOUD",4967);
		namesMap.put("TUMKUNTA   NARSA REDDY",405);
		namesMap.put("TUNDIYA SHAMBHUPRASAD BALDEVDASJI",187310);
		namesMap.put("UGRA NARASIMHA REDDY  MUKKU",2741);
		namesMap.put("UMA BHARTI",43331);
		namesMap.put("UMA MAHESWARA RAO DEVINENI",2280);
		namesMap.put("UNDHAD BAVKUBHAI NATHABHAI",188743);
		namesMap.put("UPINDERJIT KAUR",225188);
		namesMap.put("UPPALAPATI  VENKATA RAMANAMURTHY RAJU (KANNABABU)",1684);
		namesMap.put("USHA RANI  BANGARU",1983);
		namesMap.put("UTTAM KUMAR REDDY NALAMADA",5285);
		namesMap.put("V V SIVA RAMA RAJU (KALAVAPUDI SIVA)",2023);
		namesMap.put("VADDEPALLI  NARSING RAO",442);
		namesMap.put("VADODIA LALSINH UDESHINH",188136);
		namesMap.put("VAGHASIYA CHANDUBHAI BACHUBHAI",187408);
		namesMap.put("VAGHELA FAKIRBHAI RAGHABHAI",188001);
		namesMap.put("VAGHELA LILADHARBHAI KHODAJI",38448);
		namesMap.put("VAGHELA MAHENDRASINH SHANKARSINH",188051);
		namesMap.put("VAGHELA SHANKARBHAI DESAIBHAI",168261);
		namesMap.put("VAJUBHAI VALA",187393);
		namesMap.put("VAKITI SUNITA LAXMA REDDY",349);
		namesMap.put("VAMSI MOHAN VALLABHANENI",30471);
		namesMap.put("VANANI NANUBHAI BHAGVANBHAI",188390);
		namesMap.put("VANGA  GEETHA VISWANADH",1748);
		namesMap.put("VANTERU VENUGOPAL REDDY",6100);
		namesMap.put("VASAVA CHHOTUBHAI AMARSANG",46175);
		namesMap.put("VASAVA GANPATSINH VESTABHAI",188352);
		namesMap.put("VASAVA PRABUBHAI NAGARBHAI",188357);
		namesMap.put("VASUNDHARA RAJE",47500);
		namesMap.put("VATTI  VASANT KUMAR",2055);
		namesMap.put("VAYALAR RAVI",51423);
		namesMap.put("VELAMPALLI  SRINIVASA RAO",2238);
		namesMap.put("VENKATA MYSURA REDDY MULE",6339);
		namesMap.put("VENKATA SUJAY KRISHNA RANGA RAO  RAVU",1502);
		namesMap.put("VENUGOPAL D",15457);
		namesMap.put("VENUGOPAL D",44006);
		namesMap.put("VENUGOPALA CHARY  S",87);
		namesMap.put("VIDYA STOKES",238976);
		namesMap.put("VIJAYA HARSHA KUMAR GADDAM",30418);
		namesMap.put("VIJAYA KUMAR  THYNALA",1587);
		namesMap.put("VIJAYA PRASAD  MALLA",1601);
		namesMap.put("VIJAYA SHANTHI M",30173);
		namesMap.put("VIJAYAN A K S",35661);
		namesMap.put("VIJAYAN A K S",40267);
		namesMap.put("VIJAYARAMARAJU  SATRUCHERLA",1416);
		namesMap.put("VINCENT H PALA",34485);
		namesMap.put("VINOD KUMAR BOINPALLY",30140);
		namesMap.put("VIRBHADRA SINGH",32259);
		namesMap.put("VISWANATHAN P",21243);
		namesMap.put("VORA RAMANLAL ISHWARLAL",189015);
		namesMap.put("VYAS JAYNARAYAN NARMADA SHANKAR",276465);
		namesMap.put("Y  BALANAGI REDDY",3121);
		namesMap.put("Y S JAGAN MOHAN REDDY",30580);
		namesMap.put("Y S RAJASEKHAR REDDY",2898);
		namesMap.put("Y S VIJAYAMMA",156693);
		namesMap.put("Y S VIVEKANANDA REDDY",8870);
		namesMap.put("YARAPATINENI SRINIVASA RAO",2538);
		namesMap.put("YARRAM  VENKATESWARAREDDY",2514);
		namesMap.put("YASHPAL ARYA",37126);
		namesMap.put("YENNAM SRINIVAS REDDY",276161);
		namesMap.put("YERRANNAIDU KINJARAPU",7209);
		namesMap.put("YOGESH PATEL",188255);
		namesMap.put("ZALA UDESINH PUNJAJI",188044);
		return namesMap;
	}
}
