package com.itgrids.eliteclub.model;

// Generated Apr 11, 2014 7:30:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactAkmt generated by hbm2java
 */
@Entity
@Table(name = "contact_akmt")
public class ContactAkmt implements java.io.Serializable {

	private int contactAkmtId;
	private File file;
	private ContactDetails contactDetails;
	private ContentStatusRelation contentStatusRelation;
	private Integer statusCount;
	private Date lastSentTime;
	private Date callDuaration;

	public ContactAkmt() {
	}

	public ContactAkmt(int contactAkmtId) {
		this.contactAkmtId = contactAkmtId;
	}

	public ContactAkmt(int contactAkmtId, File file,
			ContactDetails contactDetails,
			ContentStatusRelation contentStatusRelation, Integer statusCount,
			Date lastSentTime, Date callDuaration) {
		this.contactAkmtId = contactAkmtId;
		this.file = file;
		this.contactDetails = contactDetails;
		this.contentStatusRelation = contentStatusRelation;
		this.statusCount = statusCount;
		this.lastSentTime = lastSentTime;
		this.callDuaration = callDuaration;
	}

	@Id
	@Column(name = "contact_akmt_id", unique = true, nullable = false)
	public int getContactAkmtId() {
		return this.contactAkmtId;
	}

	public void setContactAkmtId(int contactAkmtId) {
		this.contactAkmtId = contactAkmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "file_id")
	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_id")
	public ContactDetails getContactDetails() {
		return this.contactDetails;
	}

	public void setContactDetails(ContactDetails contactDetails) {
		this.contactDetails = contactDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_stataus_relation_id")
	public ContentStatusRelation getContentStatusRelation() {
		return this.contentStatusRelation;
	}

	public void setContentStatusRelation(
			ContentStatusRelation contentStatusRelation) {
		this.contentStatusRelation = contentStatusRelation;
	}

	@Column(name = "status_count")
	public Integer getStatusCount() {
		return this.statusCount;
	}

	public void setStatusCount(Integer statusCount) {
		this.statusCount = statusCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_sent_time", length = 19)
	public Date getLastSentTime() {
		return this.lastSentTime;
	}

	public void setLastSentTime(Date lastSentTime) {
		this.lastSentTime = lastSentTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "call_duaration", length = 19)
	public Date getCallDuaration() {
		return this.callDuaration;
	}

	public void setCallDuaration(Date callDuaration) {
		this.callDuaration = callDuaration;
	}

}
