package com.itgrids.eliteclub.model;

// Generated Apr 11, 2014 7:30:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContentType generated by hbm2java
 */
@Entity
@Table(name = "content_type", catalog = "elite_club")
public class ContentType implements java.io.Serializable {

	private Integer contenttypeId;
	private String type;
	private Set<File> files = new HashSet<File>(0);
	private Set<ContentStatusRelation> contentStatusRelations = new HashSet<ContentStatusRelation>(
			0);

	public ContentType() {
	}

	public ContentType(String type, Set<File> files,
			Set<ContentStatusRelation> contentStatusRelations) {
		this.type = type;
		this.files = files;
		this.contentStatusRelations = contentStatusRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "contenttype_id", unique = true, nullable = false)
	public Integer getContenttypeId() {
		return this.contenttypeId;
	}

	public void setContenttypeId(Integer contenttypeId) {
		this.contenttypeId = contenttypeId;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentType")
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentType")
	public Set<ContentStatusRelation> getContentStatusRelations() {
		return this.contentStatusRelations;
	}

	public void setContentStatusRelations(
			Set<ContentStatusRelation> contentStatusRelations) {
		this.contentStatusRelations = contentStatusRelations;
	}

}
