package com.itgrids.eliteclub.model;

// Generated Apr 11, 2014 7:30:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContentStatusRelation generated by hbm2java
 */
@Entity
@Table(name = "content_status_relation")
public class ContentStatusRelation implements java.io.Serializable {

	private Integer contentStatusRelationId;
	private ContentType contentType;
	private Status status;
	private Set<ContactAkmt> contactAkmts = new HashSet<ContactAkmt>(0);

	public ContentStatusRelation() {
	}

	public ContentStatusRelation(ContentType contentType, Status status,
			Set<ContactAkmt> contactAkmts) {
		this.contentType = contentType;
		this.status = status;
		this.contactAkmts = contactAkmts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "content_status_relation_id", unique = true, nullable = false)
	public Integer getContentStatusRelationId() {
		return this.contentStatusRelationId;
	}

	public void setContentStatusRelationId(Integer contentStatusRelationId) {
		this.contentStatusRelationId = contentStatusRelationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_type_id")
	public ContentType getContentType() {
		return this.contentType;
	}

	public void setContentType(ContentType contentType) {
		this.contentType = contentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentStatusRelation")
	public Set<ContactAkmt> getContactAkmts() {
		return this.contactAkmts;
	}

	public void setContactAkmts(Set<ContactAkmt> contactAkmts) {
		this.contactAkmts = contactAkmts;
	}

}
