package com.itgrids.eliteclub.model;

// Generated Apr 11, 2014 7:30:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name = "file", catalog = "elite_club")
public class File implements java.io.Serializable {

	private Integer fileId;
	private ContentType contentType;
	private Category category;
	private byte[] content;
	private String url;
	private String description;
	private Date created;
	private Date updated;
	private Character isDeleted;
	private Set<ContactAkmt> contactAkmts = new HashSet<ContactAkmt>(0);

	public File() {
	}

	public File(ContentType contentType, Category category, byte[] content,
			String url, String description, Date created, Date updated,
			Character isDeleted, Set<ContactAkmt> contactAkmts) {
		this.contentType = contentType;
		this.category = category;
		this.content = content;
		this.url = url;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.isDeleted = isDeleted;
		this.contactAkmts = contactAkmts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "file_id", unique = true, nullable = false)
	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contenttype_id")
	public ContentType getContentType() {
		return this.contentType;
	}

	public void setContentType(ContentType contentType) {
		this.contentType = contentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "content")
	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	@Column(name = "url", length = 1000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "description", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "is_deleted", length = 1)
	public Character getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Character isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "file")
	public Set<ContactAkmt> getContactAkmts() {
		return this.contactAkmts;
	}

	public void setContactAkmts(Set<ContactAkmt> contactAkmts) {
		this.contactAkmts = contactAkmts;
	}

}
