package com.itgrids.eliteclub.model;

// Generated Apr 11, 2014 7:30:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.itgrids.eliteclub.dao.AbstractDao;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {


	private Integer userId;
	private String userName;
	private String emailId;
	private String mobileno;
	private String imeiNo;
	private Date userCreationTime;
	private Set<ContactDetails> contactDetailses = new HashSet<ContactDetails>(
			0);

	public User() {
	}

	public User(String userName, String emailId, String mobileno,
			String imeiNo, Date userCreationTime,
			Set<ContactDetails> contactDetailses) {
		this.userName = userName;
		this.emailId = emailId;
		this.mobileno = mobileno;
		this.imeiNo = imeiNo;
		this.userCreationTime = userCreationTime;
		this.contactDetailses = contactDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", length = 75)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "email_id", length = 75)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "mobileno", length = 45)
	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	@Column(name = "imei_no", length = 75)
	public String getImeiNo() {
		return this.imeiNo;
	}

	public void setImeiNo(String imeiNo) {
		this.imeiNo = imeiNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_creation_time", length = 19,insertable=false)
	public Date getUserCreationTime() {
		return this.userCreationTime;
	}

	public void setUserCreationTime(Date userCreationTime) {
		this.userCreationTime = userCreationTime;
	}

	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ContactDetails> getContactDetailses() {
		return this.contactDetailses;
	}

	public void setContactDetailses(Set<ContactDetails> contactDetailses) {
		this.contactDetailses = contactDetailses;
	}

}
