package com.itgrids.partyanalyst.utils;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Date;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itgrids.partyanalyst.excel.booth.VoterVO;


public class GeneratePdf {
  private static String FILE = "D://FirstPdf11.pdf";
  private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
      Font.BOLD);
  private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
      Font.NORMAL, BaseColor.RED);
  private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 10,
      Font.BOLD);
  private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
      Font.BOLD);

  public static void main(String[] args) {
    try {
      Document document = new Document();
      PdfWriter.getInstance(document, new FileOutputStream(FILE));
      document.open();
     // addMetaData(document);
     // addTitlePage(document);
      addContent(document);
      document.close();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  // iText allows to add metadata to the PDF which can be viewed in your Adobe
  // Reader
  // under File -> Properties
  private static void addMetaData(Document document) {
    document.addTitle("My first PDF");
    document.addSubject("Using iText");
    document.addKeywords("Java, PDF, iText");
    document.addAuthor("Lars Vogel");
    document.addCreator("Lars Vogel");
  }

  private static void addTitlePage(Document document)
      throws DocumentException {
    Paragraph preface = new Paragraph();
    // We add one empty line
    addEmptyLine(preface, 1);
    // Lets write a big header
    preface.add(new Paragraph("Title of the document", catFont));

    addEmptyLine(preface, 1);
    // Will create: Report generated by: _name, _date
    preface.add(new Paragraph("Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
        smallBold));
    addEmptyLine(preface, 3);
    preface.add(new Paragraph("This document describes something which is very important ",
        smallBold));

    addEmptyLine(preface, 8);

    preface.add(new Paragraph("This document is a preliminary version and not subject to your license agreement or any other agreement with vogella.com ;-).",
        redFont));

    document.add(preface);
    // Start a new page
    document.newPage();
  }

  private static void addContent(Document document) throws DocumentException {
   /* Anchor anchor = new Anchor("First Chapter", catFont);
    anchor.setName("First Chapter");
*/
    // Second parameter is the number of the chapter
    Chapter catPart = new Chapter(new Paragraph(), 1);

    Paragraph subPara = new Paragraph();
    Section subCatPart = catPart.addSection(subPara);
  /*  subCatPart.add(new Paragraph("Hello"));

    subPara = new Paragraph("Subcategory 2", subFont);
    subCatPart = catPart.addSection(subPara);
    subCatPart.add(new Paragraph("Paragraph 1"));
    subCatPart.add(new Paragraph("Paragraph 2"));
    subCatPart.add(new Paragraph("Paragraph 3"));

    // add a list
    createList(subCatPart);
    Paragraph paragraph = new Paragraph();
    addEmptyLine(paragraph, 5);
    subCatPart.add(paragraph);*/

    // add a table
   // createTable(subCatPart);
    try
    {
    	
    	
    createTable(document);
    createTable1(document);
    
    //age wise info
    createTable2(document);
    
    //mandal wise info
    createTable3(document);
    
    //second page Range wise Voter Addition  in Panchayats						

    createTable4(document);
    
    
    createTable5(document);
    
    createTable6(document);
    
    
    
    //age wise deleted voters
    createTable7(document);
    
  /*  
    // age wise added voters
    createTable10(document);
*/
    
    //2014 Draft Elecotral Roll Added Voters	 5th page
    createTable8(document);
    
    
  /*//2014 Draft Elecotral Roll Added Voters	 5th page
    createTable8(document);
    */
    
    createTable11(document);
    
    //2014 Draft Elecotral Roll Added Voters	 5th page
    createTable9(document);

    
    }catch(Exception e){
    	
    	e.printStackTrace();
    	
    }

   // now add all this to the document
   // document.add(catPart);

    /* // Next section
    anchor = new Anchor("Second Chapter", catFont);
    anchor.setName("Second Chapter");

    // Second parameter is the number of the chapter
    catPart = new Chapter(new Paragraph(anchor), 1);

    subPara = new Paragraph("Subcategory", subFont);
    subCatPart = catPart.addSection(subPara);
    subCatPart.add(new Paragraph("This is a very important message"));

    // now add all this to the document
    document.add(catPart);*/

  }

  private static void createTable(Document document)
      throws DocumentException {
    PdfPTable table = new PdfPTable(4);
    
    
    

    PdfPCell c1 = new PdfPCell(new Phrase("Electoral Roll" ,subFont));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    c1.setBackgroundColor(BaseColor.YELLOW);
    table.addCell(c1);

    c1 = new PdfPCell(new Phrase("Total Voters",subFont));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    c1.setBackgroundColor(BaseColor.YELLOW);
    table.addCell(c1);

    c1 = new PdfPCell(new Phrase("Male Voters"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    c1.setBackgroundColor(BaseColor.YELLOW);
    table.addCell(c1);
    
    c1 = new PdfPCell(new Phrase("Female Voters"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    c1.setBackgroundColor(BaseColor.YELLOW);
    table.addCell(c1);
    
    table.setHeaderRows(1);

    
    for(int i=0;i<6;i++)
    {
	    table.addCell("1.0");
	    table.addCell("1.1");
	    table.addCell("1.2");
	    table.addCell("1.3");
    }
    
    c1 = new PdfPCell(new Phrase("Difference"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    c1.setBackgroundColor(BaseColor.GRAY);
    table.addCell(c1);

    c1 = new PdfPCell(new Phrase("5647"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    c1.setBackgroundColor(BaseColor.GRAY);
    table.addCell(c1);

    c1 = new PdfPCell(new Phrase("2875"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    c1.setBackgroundColor(BaseColor.GRAY);
    table.addCell(c1);
    
    c1 = new PdfPCell(new Phrase("2775"));
    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    c1.setBackgroundColor(BaseColor.GRAY);
    table.addCell(c1);
    
    
   
    document.add(table);

  }
  
  private static void createTable1(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(4);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	    PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Added /Deleted Info"));
        cell.setColspan(4);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);

	    PdfPCell c1 = new PdfPCell(new Phrase("Status"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("Total"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("Male"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Female"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    table.setHeaderRows(1);

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
	    }
	    
	  
	   
	    document.add(table);

	    
	  }
  
  private static void createTable2(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(7);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	    PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Age Wise Info"));
        cell.setColspan(7);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);

	    PdfPCell c1 = new PdfPCell(new Phrase("Age Range"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("First Time Voters"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("23 - 25"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("26 - 35"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("36 - 45"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("46 - 60"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    table.setHeaderRows(1);

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
	    }
	    
	  
	   
	    document.add(table);

	    
	  }
  
  private static void createTable3(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(10);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	    PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
        cell.setColspan(10);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
       // PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Mandal/Muncipality"));
        cell.setRowspan(2);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Voters"));
        cell.setColspan(3);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Total Voters"));
        cell.setColspan(2);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        
        cell = new PdfPCell(new Phrase("Male Voters"));
        cell.setColspan(2);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Female Voters"));
        cell.setColspan(2);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        
        cell = new PdfPCell(new Phrase("2014"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("2013"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Difference"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Added"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Deleted"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Added"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Deleted"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Added"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        cell = new PdfPCell(new Phrase("Deleted"));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        
        
        
	   /* for(int i=0;i<2;i++)
	    {
	    	
	    	if(i==0)
	    	{
	    		    cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
	    	        cell.setColspan(3);
	    	        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
	    	        cell.setBackgroundColor(BaseColor.YELLOW);
	    	        table.addCell(cell);
	    	        
	    	        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
	    	        cell.setColspan(2);
	    	        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
	    	        cell.setBackgroundColor(BaseColor.YELLOW);
	    	        table.addCell(cell);
	    	        
	    	        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
	    	        cell.setColspan(2);
	    	        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
	    	        cell.setBackgroundColor(BaseColor.YELLOW);
	    	        table.addCell(cell);
	    	        
	    	        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
	    	        cell.setColspan(2);
	    	        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
	    	        cell.setBackgroundColor(BaseColor.YELLOW);
	    	        table.addCell(cell);
	    	        
	    	        
	    	        
	    	        table.addCell("1.0");
	    		    table.addCell("1.1");
	    		    table.addCell("1.2");
	    		
	    		
	    	}else
	    	{
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
	    	}
		    table.addCell("1.9");
		    table.addCell("1.10");
	    }
	    */
        
       // PdfPCell cell;
      /*  // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
        cell.setColspan(10);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);

	    PdfPCell c1 = new PdfPCell(new Phrase("Age Range"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("First Time Voters"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("23 - 25"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("26 - 35"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("36 - 45"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("46 - 60"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    table.setHeaderRows(1);*/

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
		    table.addCell("1.9");
		    //table.addCell("1.10");
	    }
	    
	  
	   
	    document.add(table);

	    document.newPage();

	  }
  
  
  /*private static void createTable3(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(10);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	    PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
        cell.setColspan(10);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
       // PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Mandal/Muncipality"));
        cell.setRowspan(2);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        
        
	    for(int i=0;i<2;i++)
	    {
	    	
	    	if(i==0)
	    	{
	    		    cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
	    	        cell.setColspan(3);
	    	        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
	    	        cell.setBackgroundColor(BaseColor.YELLOW);
	    	        table.addCell(cell);
	    	        
	    	        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
	    	        cell.setColspan(2);
	    	        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
	    	        cell.setBackgroundColor(BaseColor.YELLOW);
	    	        table.addCell(cell);
	    	        
	    	        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
	    	        cell.setColspan(2);
	    	        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
	    	        cell.setBackgroundColor(BaseColor.YELLOW);
	    	        table.addCell(cell);
	    	        
	    	        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
	    	        cell.setColspan(2);
	    	        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
	    	        cell.setBackgroundColor(BaseColor.YELLOW);
	    	        table.addCell(cell);
	    	        
	    	        
	    	        
	    	        table.addCell("1.0");
	    		    table.addCell("1.1");
	    		    table.addCell("1.2");
	    		
	    		
	    	}else
	    	{
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
	    	}
		    table.addCell("1.9");
		    table.addCell("1.10");
	    }
	    
        
       // PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Mandal/Muncipality Wise Information"));
        cell.setColspan(10);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);

	    PdfPCell c1 = new PdfPCell(new Phrase("Age Range"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("First Time Voters"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("23 - 25"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("26 - 35"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("36 - 45"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("46 - 60"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    table.setHeaderRows(1);

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
		    table.addCell("1.9");
		    table.addCell("1.10");
	    }
	    
	  
	   
	    document.add(table);

	    document.newPage();

	  }*/
  
  private static void createTable4(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(9);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	    PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Range wise Voter Addition  in Panchayats"));
        cell.setColspan(9);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        								

	    PdfPCell c1 = new PdfPCell(new Phrase("Row Labels"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("1 - 50"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("51-100"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("101 - 150"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("151 - 200"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("201 - 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Above 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("No Changes"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Grand Total"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	 /*   c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);*/
	    table.setHeaderRows(1);

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
		    //table.addCell("1.9");
		   // table.addCell("1.10");
	    }
	    
	    
	    c1 = new PdfPCell(new Phrase("Difference"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("5647"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("2875"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	  
	   
	    document.add(table);


	  }
  
  
  
  private static void createTable5(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(7);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	    PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Range wise Voter Deletion  in Panchayats"));
        cell.setColspan(7);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        								

	    PdfPCell c1 = new PdfPCell(new Phrase("Row Labels"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("1 - 50"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("51-100"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("101 - 150"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("151 - 200"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("201 - 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Above 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	 
	 /*   c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);*/
	    table.setHeaderRows(1);

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		   // table.addCell("1.7");
		   // table.addCell("1.8");
		    //table.addCell("1.9");
		   // table.addCell("1.10");
	    }
	    
	    
	    c1 = new PdfPCell(new Phrase("Difference"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("5647"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("2875"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	  
	   
	    document.add(table);


	  }
  
  
  private static void createTable6(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(5);
	    
	    document.newPage();
	    
	 /*   Paragraph gallery = new Paragraph("RAYADURG CONSTITUENCY 2013 Vs 2014 Added Deleted Voters", new Font(
				Font.FontFamily.TIMES_ROMAN, 13, Font.BOLD,
				BaseColor.GRAY));		
		 gallery.setAlignment(Paragraph.ALIGN_CENTER);		
		
		document.add(gallery);*/

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	    PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("RAYADURG CONSTITUENCY 2013 Vs 2014 Added Deleted Voters"));
        cell.setColspan(5);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);
        								

	    PdfPCell c1 = new PdfPCell(new Phrase("Tehsil_name"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("Panchayat_name"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("Added"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Deleted"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("Grand Total"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	 /*   
	    c1 = new PdfPCell(new Phrase("201 - 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Above 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);*/
	    
	 
	 /*   c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);*/
	    table.setHeaderRows(1);

	    
	    for(int i=0;i<5;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    //table.addCell("1.5");
		    //table.addCell("1.6");
		   // table.addCell("1.7");
		   // table.addCell("1.8");
		    //table.addCell("1.9");
		   // table.addCell("1.10");
	    }
	    
	    
	    c1 = new PdfPCell(new Phrase("Difference"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("5647"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("2875"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	  
	   
	    document.add(table);


	  }
  
  private static void createTable7(Document document)
	      throws DocumentException {
	  document.newPage();
	    PdfPTable table = new PdfPTable(9);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	    
	    Paragraph gallery = new Paragraph("Age Wise Added  Voters", new Font(
				Font.FontFamily.TIMES_ROMAN, 13, Font.BOLD,
				BaseColor.GRAY));		
		 gallery.setAlignment(Paragraph.ALIGN_CENTER);		
		
		document.add(gallery);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	  /*  PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Range wise Voter Addition  in Panchayats"));
        cell.setColspan(9);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);*/
        								

	    PdfPCell c1 = new PdfPCell(new Phrase("Tehsil_Name"));
	    //c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    c1.setRowspan(2);
	    table.addCell(c1);

	 /*   c1 = new PdfPCell(new Phrase("1 - 50"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/

	    c1 = new PdfPCell(new Phrase("Panchayat_Name"));
	   // c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    c1.setRowspan(2);
	    table.addCell(c1);
	    
	 /*   c1 = new PdfPCell(new Phrase("101 - 150"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/
	    c1 = new PdfPCell(new Phrase("151 - 200"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    c1.setColspan(7);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("201 - 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Above 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("No Changes"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Grand Total"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	  /*  
	    c1 = new PdfPCell(new Phrase("Row Labels"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/

	    c1 = new PdfPCell(new Phrase("1 - 50"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("51-100"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("101 - 150"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	  
	  //  table.setHeaderRows(1);

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
		    //table.addCell("1.9");
		   // table.addCell("1.10");
	    }
	    
	    
	    c1 = new PdfPCell(new Phrase("Difference"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("5647"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("2875"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	  
	   
	    document.add(table);


	  }
  
  
  private static void createTable10(Document document)
	      throws DocumentException {
	  document.newPage();
	    PdfPTable table = new PdfPTable(9);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	    
	    Paragraph gallery = new Paragraph("Age Wise Deleted  Voters", new Font(
				Font.FontFamily.TIMES_ROMAN, 13, Font.BOLD,
				BaseColor.GRAY));		
		 gallery.setAlignment(Paragraph.ALIGN_CENTER);		
		
		document.add(gallery);
	 	    
        document.add( new Paragraph(" ") );
        document.add( new Paragraph(" ") );
	    
	    
	  /*  PdfPCell cell;
        // we add a cell with colspan 3
        cell = new PdfPCell(new Phrase("Range wise Voter Addition  in Panchayats"));
        cell.setColspan(9);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);*/
        								

	    PdfPCell c1 = new PdfPCell(new Phrase("Row Labels"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    c1.setRowspan(2);
	    table.addCell(c1);

	 /*   c1 = new PdfPCell(new Phrase("1 - 50"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/

	    c1 = new PdfPCell(new Phrase("51-100"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    c1.setRowspan(2);
	    table.addCell(c1);
	    
	 /*   c1 = new PdfPCell(new Phrase("101 - 150"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/
	    c1 = new PdfPCell(new Phrase("151 - 200"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("201 - 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Above 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("No Changes"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Grand Total"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	  /*  
	    c1 = new PdfPCell(new Phrase("Row Labels"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/

	    c1 = new PdfPCell(new Phrase("1 - 50"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("51-100"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("101 - 150"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("151 - 200"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("201 - 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Above 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("No Changes"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Grand Total"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	 /*   c1 = new PdfPCell(new Phrase("60-Above"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);*/
	    table.setHeaderRows(1);

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
		    //table.addCell("1.9");
		   // table.addCell("1.10");
	    }
	    
	    
	    c1 = new PdfPCell(new Phrase("Difference"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("5647"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("2875"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	  
	   
	    document.add(table);


	  }
  
  
  private static void createTable8(Document document)
	      throws DocumentException {
	  document.newPage();
	    PdfPTable table = new PdfPTable(9);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	    
	    Paragraph gallery = new Paragraph("Age Wise Deleted  Voters", new Font(
				Font.FontFamily.TIMES_ROMAN, 13, Font.BOLD,
				BaseColor.GRAY));		
		 gallery.setAlignment(Paragraph.ALIGN_CENTER);		
		
		document.add(gallery);
	 	    
      document.add( new Paragraph(" ") );
      document.add( new Paragraph(" ") );
	    
	    
	  /*  PdfPCell cell;
      // we add a cell with colspan 3
      cell = new PdfPCell(new Phrase("Range wise Voter Addition  in Panchayats"));
      cell.setColspan(9);
      cell.setHorizontalAlignment(Element.ALIGN_CENTER);
      cell.setBackgroundColor(BaseColor.YELLOW);
      table.addCell(cell);*/
      								

	    PdfPCell c1 = new PdfPCell(new Phrase("Tehsil_Name"));
	    //c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    c1.setRowspan(2);
	    table.addCell(c1);

	 /*   c1 = new PdfPCell(new Phrase("1 - 50"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/

	    c1 = new PdfPCell(new Phrase("Panchayat_Name"));
	   // c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    c1.setRowspan(2);
	    table.addCell(c1);
	    
	 /*   c1 = new PdfPCell(new Phrase("101 - 150"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/
	    c1 = new PdfPCell(new Phrase("151 - 200"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    c1.setColspan(7);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("201 - 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Above 300"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("No Changes"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("Grand Total"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	  /*  
	    c1 = new PdfPCell(new Phrase("Row Labels"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);*/

	    c1 = new PdfPCell(new Phrase("1 - 50"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("51-100"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("101 - 150"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	  
	  //  table.setHeaderRows(1);

	    
	    for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
		    //table.addCell("1.9");
		   // table.addCell("1.10");
	    }
	    
	    
	    c1 = new PdfPCell(new Phrase("Difference"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("5647"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("2875"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("2775"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.GRAY);
	    table.addCell(c1);
	    
	  
	   
	    document.add(table);


	  }
  
  
  private static void createTable9(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(10);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	 	    
	    Paragraph gallery = new Paragraph("2014 Draft Elecotral Roll Deleted Voters", new Font(
				Font.FontFamily.TIMES_ROMAN, 13, Font.BOLD,
				BaseColor.GRAY));		
		 gallery.setAlignment(Paragraph.ALIGN_CENTER);		
		
		document.add(gallery);
	    
		 document.add( new Paragraph(" ") );
		 document.add( new Paragraph(" ") );
	    PdfPCell cell;
        // we add a cell with colspan 3
    /*    cell = new PdfPCell(new Phrase("2014 Draft Elecotral Roll Deleted Voters"));
        cell.setColspan(10);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);*/

	    PdfPCell c1 = new PdfPCell(new Phrase("TEHSIL_NAME"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("PANCHAYAT_NAME"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("PART_NO"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("VOTER_ID"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("NAME"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("HOUSE_NO"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("GENDER"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("AGE"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("RELATIVE_NAME"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("RELATIONSHIP"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    table.setHeaderRows(1);
	    
	 // java.util.List<VoterVO> voters  =new ArrayList<VoterVO>();
	    
	    java.util.List<VoterVO> voters  = setVoterDetails();
	    
	    for(VoterVO voter:voters){
	    	
	    	    table.addCell(checkForNull(voter.getTownShip()));
			    table.addCell(checkForNull(voter.getPanchayatName()));
			    table.addCell(checkForNull(voter.getBoothName()));
			    table.addCell(checkForNull(voter.getVoterIDCardNo()));
			    table.addCell(checkForNull(voter.getFirstName()));
			    table.addCell(checkForNull(voter.getHouseNo()));
			    table.addCell(checkForNull(voter.getGender()));
			    table.addCell(checkForNull(voter.getAge().toString()));
			    table.addCell(checkForNull(voter.getRelativeFirstName()));
			    table.addCell(checkForNull(voter.getRelationshipType()));
	   
	    	}

	    
	    /*for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
		    table.addCell("1.9");
		    table.addCell("1.10");
	    }*/
	    
	  
	   
	    document.add(table);

	    document.newPage();

	  }
  
  private static void createTable11(Document document)
	      throws DocumentException {
	    PdfPTable table = new PdfPTable(10);

	    // t.setBorderColor(BaseColor.GRAY);
	    // t.setPadding(4);
	    // t.setSpacing(4);
	    // t.setBorderWidth(1);
	 	    
	    Paragraph gallery = new Paragraph("2014 Draft Elecotral Roll Added Voters", new Font(
				Font.FontFamily.TIMES_ROMAN, 13, Font.BOLD,
				BaseColor.GRAY));		
		 gallery.setAlignment(Paragraph.ALIGN_CENTER);		
		
		document.add(gallery);
	    
		 document.add( new Paragraph(" ") );
		 document.add( new Paragraph(" ") );
	    PdfPCell cell;
        // we add a cell with colspan 3
    /*    cell = new PdfPCell(new Phrase("2014 Draft Elecotral Roll Deleted Voters"));
        cell.setColspan(10);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.YELLOW);
        table.addCell(cell);*/

	    PdfPCell c1 = new PdfPCell(new Phrase("TEHSIL_NAME"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("PANCHAYAT_NAME"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);

	    c1 = new PdfPCell(new Phrase("PART_NO"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("VOTER_ID"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    c1 = new PdfPCell(new Phrase("NAME"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("HOUSE_NO"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("GENDER"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("AGE"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("RELATIVE_NAME"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    
	    c1 = new PdfPCell(new Phrase("RELATIONSHIP"));
	    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	    c1.setBackgroundColor(BaseColor.YELLOW);	    
	    table.addCell(c1);
	    table.setHeaderRows(1);
	    
	 // java.util.List<VoterVO> voters  =new ArrayList<VoterVO>();
	    
	    java.util.List<VoterVO> voters  = setVoterDetails();
	    
	    for(VoterVO voter:voters){
	    	
	    	    table.addCell(checkForNull(voter.getTownShip()));
			    table.addCell(checkForNull(voter.getPanchayatName()));
			    table.addCell(checkForNull(voter.getBoothName()));
			    table.addCell(checkForNull(voter.getVoterIDCardNo()));
			    table.addCell(checkForNull(voter.getFirstName()));
			    table.addCell(checkForNull(voter.getHouseNo()));
			    table.addCell(checkForNull(voter.getGender()));
			    table.addCell(checkForNull(voter.getAge().toString()));
			    table.addCell(checkForNull(voter.getRelativeFirstName()));
			    table.addCell(checkForNull(voter.getRelationshipType()));
	   
	    	}

	    
	    /*for(int i=0;i<3;i++)
	    {
		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("1.3");
		    table.addCell("1.4");
		    table.addCell("1.5");
		    table.addCell("1.6");
		    table.addCell("1.7");
		    table.addCell("1.8");
		    table.addCell("1.9");
		    table.addCell("1.10");
	    }*/
	    
	  
	   
	    document.add(table);

	    document.newPage();

	  }
  
  
  
  
  

  private static void createList(Section subCatPart) {
    List list = new List(true, false, 10);
    list.add(new ListItem("First point"));
    list.add(new ListItem("Second point"));
    list.add(new ListItem("Third point"));
    subCatPart.add(list);
  }
  
  public static String checkForNull(String value)
  {
	  return value == null ? "" : value;
	  
  }

  private static void addEmptyLine(Paragraph paragraph, int number) {
    for (int i = 0; i < number; i++) {
      paragraph.add(new Paragraph(" "));
    }
  }
  
  
  public static java.util.List<VoterVO> setVoterDetails()
  {
	  
	  java.util.List<VoterVO> list = new ArrayList<VoterVO>();
	  
	  
	  VoterVO voter1 = new VoterVO();
	  voter1.setTownShip("D.Hirehal");
	  voter1.setPanchayatName("MALAPANAGUDI");
	  voter1.setBoothName("1");
	  voter1.setVoterIDCardNo("VoterId");
	  voter1.setFirstName("First Name");
	  voter1.setHouseNo("12-12");
	  voter1.setGender("Male");
	  voter1.setAge(22L);
	  voter1.setRelativeFirstName("Relative Name");
	  voter1.setRelationshipType("Realtion");
	  
	  
	  VoterVO voter2 = new VoterVO();
	  voter2.setTownShip("D.Hirehal");
	  voter2.setPanchayatName("MALAPANAGUDI");
	  voter2.setBoothName("1");
	  voter2.setVoterIDCardNo("VoterId");
	  voter2.setFirstName("First Name");
	  voter2.setHouseNo("12-12");
	  voter2.setGender("Male");
	  voter2.setAge(22L);
	  voter2.setRelativeFirstName("Relative Name");
	  voter2.setRelationshipType("Realtion");
	  
	  
	  VoterVO voter3 = new VoterVO();
	  voter3.setTownShip("D.Hirehal");
	  voter3.setPanchayatName("MALAPANAGUDI");
	  voter3.setBoothName("1");
	  voter3.setVoterIDCardNo("VoterId");
	  voter3.setFirstName("First Name");
	  voter3.setHouseNo("12-12");
	  voter3.setGender("Male");
	  voter3.setAge(22L);
	  voter3.setRelativeFirstName("Relative Name");
	  voter3.setRelationshipType("Realtion");
	  
	  list.add(voter1);
	  list.add(voter2);
	  list.add(voter3);
	  
	  return list;
	  
	  
  }
} 