
package com.itgrids.survey.soa.endpoints.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPWebServiceEndPointImplService", targetNamespace = "http://impl.endpoints.soa.survey.itgrids.com/", wsdlLocation = "http://74.208.7.129/Survey1/SOAWebService?wsdl")
public class SOAPWebServiceEndPointImplService
    extends Service
{

    private final static URL SOAPWEBSERVICEENDPOINTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPWEBSERVICEENDPOINTIMPLSERVICE_EXCEPTION;
    private final static QName SOAPWEBSERVICEENDPOINTIMPLSERVICE_QNAME = new QName("http://impl.endpoints.soa.survey.itgrids.com/", "SOAPWebServiceEndPointImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://74.208.7.129/Survey1/SOAWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPWEBSERVICEENDPOINTIMPLSERVICE_WSDL_LOCATION = url;
        SOAPWEBSERVICEENDPOINTIMPLSERVICE_EXCEPTION = e;
    }

    public SOAPWebServiceEndPointImplService() {
        super(__getWsdlLocation(), SOAPWEBSERVICEENDPOINTIMPLSERVICE_QNAME);
    }

    public SOAPWebServiceEndPointImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPWEBSERVICEENDPOINTIMPLSERVICE_QNAME, features);
    }

    public SOAPWebServiceEndPointImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPWEBSERVICEENDPOINTIMPLSERVICE_QNAME);
    }

    public SOAPWebServiceEndPointImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPWEBSERVICEENDPOINTIMPLSERVICE_QNAME, features);
    }

    public SOAPWebServiceEndPointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPWebServiceEndPointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPWebServiceEndPoint
     */
    @WebEndpoint(name = "SOAPWebServiceEndPointPort")
    public SOAPWebServiceEndPoint getSOAPWebServiceEndPointPort() {
        return super.getPort(new QName("http://impl.endpoints.soa.survey.itgrids.com/", "SOAPWebServiceEndPointPort"), SOAPWebServiceEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPWebServiceEndPoint
     */
    @WebEndpoint(name = "SOAPWebServiceEndPointPort")
    public SOAPWebServiceEndPoint getSOAPWebServiceEndPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.endpoints.soa.survey.itgrids.com/", "SOAPWebServiceEndPointPort"), SOAPWebServiceEndPoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPWEBSERVICEENDPOINTIMPLSERVICE_EXCEPTION!= null) {
            throw SOAPWEBSERVICEENDPOINTIMPLSERVICE_EXCEPTION;
        }
        return SOAPWEBSERVICEENDPOINTIMPLSERVICE_WSDL_LOCATION;
    }

}
