
package com.itgrids.survey.soa.endpoints.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SOAPWebServiceEndPointImplService", targetNamespace = "http://impl.endpoints.soa.survey.itgrids.com/", wsdlLocation = "http://74.208.7.129:8080/Survey1/SOAWebService?wsdl")
public class SOAPWebServiceEndPointImplService
    extends Service
{

    private final static URL SOAPWEBSERVICEENDPOINTIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.itgrids.survey.soa.endpoints.impl.SOAPWebServiceEndPointImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.itgrids.survey.soa.endpoints.impl.SOAPWebServiceEndPointImplService.class.getResource(".");
            url = new URL(baseUrl, "http://74.208.7.129:8080/Survey1/SOAWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://74.208.7.129:8080/Survey1/SOAWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SOAPWEBSERVICEENDPOINTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public SOAPWebServiceEndPointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPWebServiceEndPointImplService() {
        super(SOAPWEBSERVICEENDPOINTIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.endpoints.soa.survey.itgrids.com/", "SOAPWebServiceEndPointImplService"));
    }

    /**
     * 
     * @return
     *     returns SOAPWebServiceEndPoint
     */
    @WebEndpoint(name = "SOAPWebServiceEndPointPort")
    public SOAPWebServiceEndPoint getSOAPWebServiceEndPointPort() {
        return super.getPort(new QName("http://impl.endpoints.soa.survey.itgrids.com/", "SOAPWebServiceEndPointPort"), SOAPWebServiceEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPWebServiceEndPoint
     */
    @WebEndpoint(name = "SOAPWebServiceEndPointPort")
    public SOAPWebServiceEndPoint getSOAPWebServiceEndPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.endpoints.soa.survey.itgrids.com/", "SOAPWebServiceEndPointPort"), SOAPWebServiceEndPoint.class, features);
    }

}
