
package com.itgrids.survey.soa.endpoints.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.itgrids.survey.soa.endpoints.ElectionComparisonVO;
import com.itgrids.survey.soa.endpoints.GenericVO;
import com.itgrids.survey.soa.endpoints.ObjectFactory;
import com.itgrids.survey.soa.endpoints.OptionVO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPWebServiceEndPoint", targetNamespace = "http://endpoints.soa.survey.itgrids.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPWebServiceEndPoint {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.itgrids.survey.soa.endpoints.ElectionComparisonVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPartyWiseCountDetailsForSelectedSurveys", targetNamespace = "http://endpoints.soa.survey.itgrids.com/", className = "com.itgrids.survey.soa.endpoints.GetPartyWiseCountDetailsForSelectedSurveys")
    @ResponseWrapper(localName = "getPartyWiseCountDetailsForSelectedSurveysResponse", targetNamespace = "http://endpoints.soa.survey.itgrids.com/", className = "com.itgrids.survey.soa.endpoints.GetPartyWiseCountDetailsForSelectedSurveysResponse")
    @Action(input = "http://endpoints.soa.survey.itgrids.com/SOAPWebServiceEndPoint/getPartyWiseCountDetailsForSelectedSurveysRequest", output = "http://endpoints.soa.survey.itgrids.com/SOAPWebServiceEndPoint/getPartyWiseCountDetailsForSelectedSurveysResponse")
    public ElectionComparisonVO getPartyWiseCountDetailsForSelectedSurveys(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Long> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.itgrids.survey.soa.endpoints.OptionVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTop5CastePeopleOpnionOnParty", targetNamespace = "http://endpoints.soa.survey.itgrids.com/", className = "com.itgrids.survey.soa.endpoints.GetTop5CastePeopleOpnionOnParty")
    @ResponseWrapper(localName = "getTop5CastePeopleOpnionOnPartyResponse", targetNamespace = "http://endpoints.soa.survey.itgrids.com/", className = "com.itgrids.survey.soa.endpoints.GetTop5CastePeopleOpnionOnPartyResponse")
    @Action(input = "http://endpoints.soa.survey.itgrids.com/SOAPWebServiceEndPoint/getTop5CastePeopleOpnionOnPartyRequest", output = "http://endpoints.soa.survey.itgrids.com/SOAPWebServiceEndPoint/getTop5CastePeopleOpnionOnPartyResponse")
    public List<OptionVO> getTop5CastePeopleOpnionOnParty(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Long> arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.itgrids.survey.soa.endpoints.GenericVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGenderWiseReportForSurveyAnalysis", targetNamespace = "http://endpoints.soa.survey.itgrids.com/", className = "com.itgrids.survey.soa.endpoints.GetGenderWiseReportForSurveyAnalysis")
    @ResponseWrapper(localName = "getGenderWiseReportForSurveyAnalysisResponse", targetNamespace = "http://endpoints.soa.survey.itgrids.com/", className = "com.itgrids.survey.soa.endpoints.GetGenderWiseReportForSurveyAnalysisResponse")
    @Action(input = "http://endpoints.soa.survey.itgrids.com/SOAPWebServiceEndPoint/getGenderWiseReportForSurveyAnalysisRequest", output = "http://endpoints.soa.survey.itgrids.com/SOAPWebServiceEndPoint/getGenderWiseReportForSurveyAnalysisResponse")
    public List<GenericVO> getGenderWiseReportForSurveyAnalysis(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Long> arg2);

}
